use serde::{Deserialize, Serialize};

use crate::ids::ServerPacketId;
use crate::packets::{ClientPacket, ServerPacket};

pub fn server_packet_raw_name(packet_id: ServerPacketId) -> &'static str {
    match packet_id {
        ServerPacketId::TimeOfDay => "TimeOfDay",
        ServerPacketId::ChangeAMode => "ChangeAMode",
        ServerPacketId::ChangePMode => "ChangePMode",
        ServerPacketId::BaseStatsInfo => "BaseStatsInfo",
        ServerPacketId::HeroBaseStatsInfo => "HeroBaseStatsInfo",
        ServerPacketId::HeroInformation => "HeroInformation",
        ServerPacketId::NPCMarket => "NPCMarket",
        ServerPacketId::NPCMarketPage => "NPCMarketPage",
        ServerPacketId::DefaultNPC => "DefaultNPC",
        ServerPacketId::NPCUpdate => "NPCUpdate",
        ServerPacketId::NPCResponse => "NPCResponse",
        ServerPacketId::CompleteQuest => "CompleteQuest",
        ServerPacketId::ReceiveMail => "ReceiveMail",
        ServerPacketId::MailLockedItem => "MailLockedItem",
        ServerPacketId::MailSendRequest => "MailSendRequest",
        ServerPacketId::MailSent => "MailSent",
        ServerPacketId::ParcelCollected => "ParcelCollected",
        ServerPacketId::MailCost => "MailCost",
        ServerPacketId::FriendUpdate => "FriendUpdate",
        ServerPacketId::NewIntelligentCreature => "NewIntelligentCreature",
        ServerPacketId::UpdateIntelligentCreatureList => "UpdateIntelligentCreatureList",
        ServerPacketId::IntelligentCreatureEnableRename => "IntelligentCreatureEnableRename",
        ServerPacketId::IntelligentCreaturePickup => "IntelligentCreaturePickup",
        ServerPacketId::LoverUpdate => "LoverUpdate",
        ServerPacketId::MentorUpdate => "MentorUpdate",
        ServerPacketId::GuildBuffList => "GuildBuffList",
        ServerPacketId::GameShopInfo => "GameShopInfo",
        _ => "Raw",
    }
}

pub fn server_packet_raw_display_name(packet_id: ServerPacketId) -> String {
    let name = server_packet_raw_name(packet_id);
    if name == "Raw" {
        format!("{packet_id:?}")
    } else {
        name.to_string()
    }
}

pub fn server_packet_display_name(packet: &ServerPacket) -> String {
    let name = server_packet_name(packet);
    if name == "Raw" {
        format!("{:?}", packet.packet_id())
    } else {
        name.to_string()
    }
}

pub fn packet_payload_hex(payload: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(payload.len() * 2);
    for byte in payload {
        output.push(HEX[(byte >> 4) as usize] as char);
        output.push(HEX[(byte & 0x0f) as usize] as char);
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::ClientMapInfo;

    #[test]
    fn packet_payload_hex_is_copyable_lowercase_hex() {
        assert_eq!(packet_payload_hex(&[0x00, 0x0f, 0xa0, 0xff]), "000fa0ff");
    }

    #[test]
    fn server_display_names_use_typed_enum_names_for_raw_fallback_ids() {
        assert_eq!(
            server_packet_raw_display_name(ServerPacketId::NewMapInfo),
            "NewMapInfo"
        );

        let packet = ServerPacket::NewMapInfo {
            map_index: 77,
            info: ClientMapInfo {
                title: "CastleGi-Ryoong".into(),
                width: 120,
                height: 220,
                big_map: 121,
                movements: vec![],
                npcs: vec![],
            },
        };
        assert_eq!(server_packet_name(&packet), "Raw");
        assert_eq!(server_packet_display_name(&packet), "NewMapInfo");
        assert_eq!(trace_server_packets(&[packet])[0].packet, "NewMapInfo");
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PacketTraceDirection {
    Client,
    Server,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PacketTraceEntry {
    pub sequence: usize,
    pub direction: PacketTraceDirection,
    pub packet_id: i16,
    pub packet: String,
}

pub fn trace_client_packets(packets: &[ClientPacket]) -> Vec<PacketTraceEntry> {
    packets
        .iter()
        .enumerate()
        .map(|(sequence, packet)| PacketTraceEntry {
            sequence,
            direction: PacketTraceDirection::Client,
            packet_id: packet.packet_id() as i16,
            packet: client_packet_name(packet).to_string(),
        })
        .collect()
}

pub fn trace_server_packets(packets: &[ServerPacket]) -> Vec<PacketTraceEntry> {
    packets
        .iter()
        .enumerate()
        .map(|(sequence, packet)| PacketTraceEntry {
            sequence,
            direction: PacketTraceDirection::Server,
            packet_id: packet.packet_id() as i16,
            packet: server_packet_display_name(packet),
        })
        .collect()
}

pub fn client_packet_name(packet: &ClientPacket) -> &'static str {
    match packet {
        ClientPacket::ClientVersion { .. } => "ClientVersion",
        ClientPacket::Disconnect => "Disconnect",
        ClientPacket::KeepAlive { .. } => "KeepAlive",
        ClientPacket::NewAccount { .. } => "NewAccount",
        ClientPacket::ChangePassword { .. } => "ChangePassword",
        ClientPacket::Login { .. } => "Login",
        ClientPacket::NewCharacter { .. } => "NewCharacter",
        ClientPacket::DeleteCharacter { .. } => "DeleteCharacter",
        ClientPacket::StartGame { .. } => "StartGame",
        ClientPacket::LogOut => "LogOut",
        ClientPacket::Turn { .. } => "Turn",
        ClientPacket::Walk { .. } => "Walk",
        ClientPacket::Run { .. } => "Run",
        ClientPacket::Chat { .. } => "Chat",
        ClientPacket::MoveItem { .. } => "MoveItem",
        ClientPacket::StoreItem { .. } => "StoreItem",
        ClientPacket::TakeBackItem { .. } => "TakeBackItem",
        ClientPacket::MergeItem { .. } => "MergeItem",
        ClientPacket::EquipItem { .. } => "EquipItem",
        ClientPacket::RemoveItem { .. } => "RemoveItem",
        ClientPacket::RemoveSlotItem { .. } => "RemoveSlotItem",
        ClientPacket::SplitItem { .. } => "SplitItem",
        ClientPacket::UseItem { .. } => "UseItem",
        ClientPacket::DropItem { .. } => "DropItem",
        ClientPacket::DepositRefineItem { .. } => "DepositRefineItem",
        ClientPacket::RetrieveRefineItem { .. } => "RetrieveRefineItem",
        ClientPacket::RefineCancel => "RefineCancel",
        ClientPacket::RefineItem { .. } => "RefineItem",
        ClientPacket::CheckRefine { .. } => "CheckRefine",
        ClientPacket::ReplaceWedRing { .. } => "ReplaceWedRing",
        ClientPacket::DepositTradeItem { .. } => "DepositTradeItem",
        ClientPacket::RetrieveTradeItem { .. } => "RetrieveTradeItem",
        ClientPacket::TakeBackHeroItem { .. } => "TakeBackHeroItem",
        ClientPacket::TransferHeroItem { .. } => "TransferHeroItem",
        ClientPacket::DeleteItem { .. } => "DeleteItem",
        ClientPacket::DropGold { .. } => "DropGold",
        ClientPacket::PickUp => "PickUp",
        ClientPacket::RequestMapInfo { .. } => "RequestMapInfo",
        ClientPacket::RequestMonsterInfo { .. } => "RequestMonsterInfo",
        ClientPacket::RequestNpcInfo { .. } => "RequestNpcInfo",
        ClientPacket::RequestItemInfo { .. } => "RequestItemInfo",
        ClientPacket::TeleportToNpc { .. } => "TeleportToNPC",
        ClientPacket::SearchMap { .. } => "SearchMap",
        ClientPacket::Inspect { .. } => "Inspect",
        ClientPacket::Observe { .. } => "Observe",
        ClientPacket::ChangeAMode { .. } => "ChangeAMode",
        ClientPacket::ChangePMode { .. } => "ChangePMode",
        ClientPacket::ChangeTrade { .. } => "ChangeTrade",
        ClientPacket::Attack { .. } => "Attack",
        ClientPacket::RangeAttack { .. } => "RangeAttack",
        ClientPacket::Harvest { .. } => "Harvest",
        ClientPacket::CallNpc { .. } => "CallNPC",
        ClientPacket::BuyItem { .. } => "BuyItem",
        ClientPacket::SellItem { .. } => "SellItem",
        ClientPacket::CraftItem { .. } => "CraftItem",
        ClientPacket::RepairItem { .. } => "RepairItem",
        ClientPacket::BuyItemBack { .. } => "BuyItemBack",
        ClientPacket::SRepairItem { .. } => "SRepairItem",
        ClientPacket::MagicKey { .. } => "MagicKey",
        ClientPacket::Magic { .. } => "Magic",
        ClientPacket::SwitchGroup { .. } => "SwitchGroup",
        ClientPacket::AddMember { .. } => "AddMember",
        ClientPacket::DelMember { .. } => "DelMember",
        ClientPacket::GroupInvite { .. } => "GroupInvite",
        ClientPacket::NewHero { .. } => "NewHero",
        ClientPacket::SetAutoPotValue { .. } => "SetAutoPotValue",
        ClientPacket::SetAutoPotItem { .. } => "SetAutoPotItem",
        ClientPacket::SetHeroBehaviour { .. } => "SetHeroBehaviour",
        ClientPacket::ChangeHero { .. } => "ChangeHero",
        ClientPacket::TownRevive => "TownRevive",
        ClientPacket::SpellToggle { .. } => "SpellToggle",
        ClientPacket::ConsignItem { .. } => "ConsignItem",
        ClientPacket::MarketSearch { .. } => "MarketSearch",
        ClientPacket::MarketRefresh => "MarketRefresh",
        ClientPacket::MarketPage { .. } => "MarketPage",
        ClientPacket::MarketBuy { .. } => "MarketBuy",
        ClientPacket::MarketGetBack { .. } => "MarketGetBack",
        ClientPacket::MarketSellNow { .. } => "MarketSellNow",
        ClientPacket::RequestUserName { .. } => "RequestUserName",
        ClientPacket::RequestChatItem { .. } => "RequestChatItem",
        ClientPacket::EditGuildMember { .. } => "EditGuildMember",
        ClientPacket::EditGuildNotice { .. } => "EditGuildNotice",
        ClientPacket::GuildInvite { .. } => "GuildInvite",
        ClientPacket::GuildNameReturn { .. } => "GuildNameReturn",
        ClientPacket::RequestGuildInfo { .. } => "RequestGuildInfo",
        ClientPacket::GuildStorageGoldChange { .. } => "GuildStorageGoldChange",
        ClientPacket::GuildStorageItemChange { .. } => "GuildStorageItemChange",
        ClientPacket::GuildWarReturn { .. } => "GuildWarReturn",
        ClientPacket::MarriageRequest => "MarriageRequest",
        ClientPacket::MarriageReply { .. } => "MarriageReply",
        ClientPacket::ChangeMarriage => "ChangeMarriage",
        ClientPacket::DivorceRequest => "DivorceRequest",
        ClientPacket::DivorceReply { .. } => "DivorceReply",
        ClientPacket::AddMentor { .. } => "AddMentor",
        ClientPacket::MentorReply { .. } => "MentorReply",
        ClientPacket::AllowMentor => "AllowMentor",
        ClientPacket::CancelMentor => "CancelMentor",
        ClientPacket::TradeRequest => "TradeRequest",
        ClientPacket::TradeReply { .. } => "TradeReply",
        ClientPacket::TradeGold { .. } => "TradeGold",
        ClientPacket::TradeConfirm { .. } => "TradeConfirm",
        ClientPacket::TradeCancel => "TradeCancel",
        ClientPacket::EquipSlotItem { .. } => "EquipSlotItem",
        ClientPacket::FishingCast { .. } => "FishingCast",
        ClientPacket::FishingChangeAutocast { .. } => "FishingChangeAutocast",
        ClientPacket::AcceptQuest { .. } => "AcceptQuest",
        ClientPacket::FinishQuest { .. } => "FinishQuest",
        ClientPacket::AbandonQuest { .. } => "AbandonQuest",
        ClientPacket::ShareQuest { .. } => "ShareQuest",
        ClientPacket::AcceptReincarnation => "AcceptReincarnation",
        ClientPacket::CancelReincarnation => "CancelReincarnation",
        ClientPacket::CombineItem { .. } => "CombineItem",
        ClientPacket::AwakeningNeedMaterials { .. } => "AwakeningNeedMaterials",
        ClientPacket::AwakeningLockedItem { .. } => "AwakeningLockedItem",
        ClientPacket::Awakening { .. } => "Awakening",
        ClientPacket::DisassembleItem { .. } => "DisassembleItem",
        ClientPacket::DowngradeAwakening { .. } => "DowngradeAwakening",
        ClientPacket::ResetAddedItem { .. } => "ResetAddedItem",
        ClientPacket::SendMail { .. } => "SendMail",
        ClientPacket::ReadMail { .. } => "ReadMail",
        ClientPacket::CollectParcel { .. } => "CollectParcel",
        ClientPacket::DeleteMail { .. } => "DeleteMail",
        ClientPacket::LockMail { .. } => "LockMail",
        ClientPacket::MailLockedItem { .. } => "MailLockedItem",
        ClientPacket::MailCost { .. } => "MailCost",
        ClientPacket::UpdateIntelligentCreature { .. } => "UpdateIntelligentCreature",
        ClientPacket::IntelligentCreaturePickup { .. } => "IntelligentCreaturePickup",
        ClientPacket::RequestIntelligentCreatureUpdates { .. } => {
            "RequestIntelligentCreatureUpdates"
        }
        ClientPacket::AddFriend { .. } => "AddFriend",
        ClientPacket::RemoveFriend { .. } => "RemoveFriend",
        ClientPacket::RefreshFriends => "RefreshFriends",
        ClientPacket::AddMemo { .. } => "AddMemo",
        ClientPacket::GuildBuffUpdate { .. } => "GuildBuffUpdate",
        ClientPacket::NpcConfirmInput { .. } => "NPCConfirmInput",
        ClientPacket::GameShopBuy { .. } => "GameshopBuy",
        ClientPacket::ReportIssue { .. } => "ReportIssue",
        ClientPacket::GetRanking { .. } => "GetRanking",
        ClientPacket::OpenDoor { .. } => "Opendoor",
        ClientPacket::GetRentedItems => "GetRentedItems",
        ClientPacket::ItemRentalRequest => "ItemRentalRequest",
        ClientPacket::ItemRentalFee { .. } => "ItemRentalFee",
        ClientPacket::ItemRentalPeriod { .. } => "ItemRentalPeriod",
        ClientPacket::DepositRentalItem { .. } => "DepositRentalItem",
        ClientPacket::RetrieveRentalItem { .. } => "RetrieveRentalItem",
        ClientPacket::CancelItemRental => "CancelItemRental",
        ClientPacket::ItemRentalLockFee => "ItemRentalLockFee",
        ClientPacket::ItemRentalLockItem => "ItemRentalLockItem",
        ClientPacket::ConfirmItemRental => "ConfirmItemRental",
        ClientPacket::GuildTerritoryPage { .. } => "GuildTerritoryPage",
        ClientPacket::PurchaseGuildTerritory { .. } => "PurchaseGuildTerritory",
        ClientPacket::UnlockStorage { .. } => "UnlockStorage",
        ClientPacket::SetStoragePassword { .. } => "SetStoragePassword",
        ClientPacket::RemoveStoragePassword { .. } => "RemoveStoragePassword",
    }
}

pub fn server_packet_name(packet: &ServerPacket) -> &'static str {
    match packet {
        ServerPacket::Raw { packet_id, .. } => server_packet_raw_name(*packet_id),
        ServerPacket::TimeOfDay { .. } => "TimeOfDay",
        ServerPacket::ChangeAMode { .. } => "ChangeAMode",
        ServerPacket::ChangePMode { .. } => "ChangePMode",
        ServerPacket::BaseStatsInfo { .. } => "BaseStatsInfo",
        ServerPacket::HeroBaseStatsInfo { .. } => "HeroBaseStatsInfo",
        ServerPacket::HeroInformation { .. } => "HeroInformation",
        ServerPacket::NPCMarket { .. } => "NPCMarket",
        ServerPacket::NPCMarketPage { .. } => "NPCMarketPage",
        ServerPacket::Connected => "Connected",
        ServerPacket::ClientVersion { .. } => "ClientVersion",
        ServerPacket::Disconnect { .. } => "Disconnect",
        ServerPacket::KeepAlive { .. } => "KeepAlive",
        ServerPacket::NewAccount { .. } => "NewAccount",
        ServerPacket::ChangePassword { .. } => "ChangePassword",
        ServerPacket::ChangePasswordBanned { .. } => "ChangePasswordBanned",
        ServerPacket::Login { .. } => "Login",
        ServerPacket::LoginBanned { .. } => "LoginBanned",
        ServerPacket::LoginSuccess { .. } => "LoginSuccess",
        ServerPacket::NewCharacter { .. } => "NewCharacter",
        ServerPacket::NewCharacterSuccess { .. } => "NewCharacterSuccess",
        ServerPacket::DeleteCharacter { .. } => "DeleteCharacter",
        ServerPacket::DeleteCharacterSuccess { .. } => "DeleteCharacterSuccess",
        ServerPacket::StartGame { .. } => "StartGame",
        ServerPacket::StartGameBanned { .. } => "StartGameBanned",
        ServerPacket::StartGameDelay { .. } => "StartGameDelay",
        ServerPacket::MapInformation { .. } => "MapInformation",
        ServerPacket::UserInformation { .. } => "UserInformation",
        ServerPacket::UserLocation { .. } => "UserLocation",
        ServerPacket::ObjectPlayer { .. } => "ObjectPlayer",
        ServerPacket::ObjectHero { .. } => "ObjectHero",
        ServerPacket::ObjectRemove { .. } => "ObjectRemove",
        ServerPacket::ObjectTurn { .. } => "ObjectTurn",
        ServerPacket::ObjectWalk { .. } => "ObjectWalk",
        ServerPacket::ObjectRun { .. } => "ObjectRun",
        ServerPacket::ObjectBackStep { .. } => "ObjectBackStep",
        ServerPacket::ObjectSitDown { .. } => "ObjectSitDown",
        ServerPacket::Chat { .. } => "Chat",
        ServerPacket::ObjectChat { .. } => "ObjectChat",
        ServerPacket::NewItemInfo { .. } => "NewItemInfo",
        ServerPacket::NewHeroInfo { .. } => "NewHeroInfo",
        ServerPacket::MoveItem { .. } => "MoveItem",
        ServerPacket::EquipItem { .. } => "EquipItem",
        ServerPacket::MergeItem { .. } => "MergeItem",
        ServerPacket::RemoveItem { .. } => "RemoveItem",
        ServerPacket::RemoveSlotItem { .. } => "RemoveSlotItem",
        ServerPacket::DepositRefineItem { .. } => "DepositRefineItem",
        ServerPacket::RetrieveRefineItem { .. } => "RetrieveRefineItem",
        ServerPacket::RefineCancel => "RefineCancel",
        ServerPacket::RefineItem { .. } => "RefineItem",
        ServerPacket::TakeBackItem { .. } => "TakeBackItem",
        ServerPacket::StoreItem { .. } => "StoreItem",
        ServerPacket::SplitItem { .. } => "SplitItem",
        ServerPacket::SplitItem1 { .. } => "SplitItem1",
        ServerPacket::UseItem { .. } => "UseItem",
        ServerPacket::DropItem { .. } => "DropItem",
        ServerPacket::TakeBackHeroItem { .. } => "TakeBackHeroItem",
        ServerPacket::TransferHeroItem { .. } => "TransferHeroItem",
        ServerPacket::NewMonsterInfo { .. } => "NewMonsterInfo",
        ServerPacket::NewNpcInfo { .. } => "NewNpcInfo",
        ServerPacket::ObjectItem { .. } => "ObjectItem",
        ServerPacket::ObjectGold { .. } => "ObjectGold",
        ServerPacket::GainedItem { .. } => "GainedItem",
        ServerPacket::GainedGold { .. } => "GainedGold",
        ServerPacket::LoseGold { .. } => "LoseGold",
        ServerPacket::GainedCredit { .. } => "GainedCredit",
        ServerPacket::LoseCredit { .. } => "LoseCredit",
        ServerPacket::ObjectMonster { .. } => "ObjectMonster",
        ServerPacket::ObjectAttack { .. } => "ObjectAttack",
        ServerPacket::Struck { .. } => "Struck",
        ServerPacket::ObjectStruck { .. } => "ObjectStruck",
        ServerPacket::DuraChanged { .. } => "DuraChanged",
        ServerPacket::HeroHealthChanged { .. } => "HeroHealthChanged",
        ServerPacket::DeleteItem { .. } => "DeleteItem",
        ServerPacket::ObjectDied { .. } => "ObjectDied",
        ServerPacket::GainHeroExperience { .. } => "GainHeroExperience",
        ServerPacket::HeroLevelChanged { .. } => "HeroLevelChanged",
        ServerPacket::ObjectHarvest { .. } => "ObjectHarvest",
        ServerPacket::ObjectHarvested { .. } => "ObjectHarvested",
        ServerPacket::ObjectNpc { .. } => "ObjectNpc",
        ServerPacket::NPCResponse { .. } => "NPCResponse",
        ServerPacket::ObjectHide { .. } => "ObjectHide",
        ServerPacket::ObjectShow { .. } => "ObjectShow",
        ServerPacket::ObjectTeleportOut { .. } => "ObjectTeleportOut",
        ServerPacket::ObjectTeleportIn { .. } => "ObjectTeleportIn",
        ServerPacket::TeleportIn => "TeleportIn",
        ServerPacket::NPCGoods { .. } => "NPCGoods",
        ServerPacket::NPCSell => "NPCSell",
        ServerPacket::NPCRepair { .. } => "NPCRepair",
        ServerPacket::NPCSRepair { .. } => "NPCSRepair",
        ServerPacket::NPCRefine { .. } => "NPCRefine",
        ServerPacket::NPCCheckRefine => "NPCCheckRefine",
        ServerPacket::NPCCollectRefine { .. } => "NPCCollectRefine",
        ServerPacket::NPCReplaceWedRing { .. } => "NPCReplaceWedRing",
        ServerPacket::NPCStorage => "NPCStorage",
        ServerPacket::UserStorage { .. } => "UserStorage",
        ServerPacket::SellItem { .. } => "SellItem",
        ServerPacket::RepairItem { .. } => "RepairItem",
        ServerPacket::CraftItem { .. } => "CraftItem",
        ServerPacket::CombineItem { .. } => "CombineItem",
        ServerPacket::ItemUpgraded { .. } => "ItemUpgraded",
        ServerPacket::ItemRepaired { .. } => "ItemRepaired",
        ServerPacket::ItemSlotSizeChanged { .. } => "ItemSlotSizeChanged",
        ServerPacket::ItemSealChanged { .. } => "ItemSealChanged",
        ServerPacket::NewMagic { .. } => "NewMagic",
        ServerPacket::RemoveMagic { .. } => "RemoveMagic",
        ServerPacket::MagicLeveled { .. } => "MagicLeveled",
        ServerPacket::Magic { .. } => "Magic",
        ServerPacket::MagicDelay { .. } => "MagicDelay",
        ServerPacket::MagicCast { .. } => "MagicCast",
        ServerPacket::ObjectMagic { .. } => "ObjectMagic",
        ServerPacket::ObjectProjectile { .. } => "ObjectProjectile",
        ServerPacket::RangeAttack { .. } => "RangeAttack",
        ServerPacket::Pushed { .. } => "Pushed",
        ServerPacket::ObjectPushed { .. } => "ObjectPushed",
        ServerPacket::SpellToggle { .. } => "SpellToggle",
        ServerPacket::SwitchGroup { .. } => "SwitchGroup",
        ServerPacket::DeleteGroup => "DeleteGroup",
        ServerPacket::DeleteMember { .. } => "DeleteMember",
        ServerPacket::GroupInvite { .. } => "GroupInvite",
        ServerPacket::AddMember { .. } => "AddMember",
        ServerPacket::GroupMembersMap { .. } => "GroupMembersMap",
        ServerPacket::SendMemberLocation { .. } => "SendMemberLocation",
        ServerPacket::ObjectRevived { .. } => "ObjectRevived",
        ServerPacket::ObjectEffect { .. } => "ObjectEffect",
        ServerPacket::ObjectHealth { .. } => "ObjectHealth",
        ServerPacket::ObjectMana { .. } => "ObjectMana",
        ServerPacket::MapEffect { .. } => "MapEffect",
        ServerPacket::AllowObserve { .. } => "AllowObserve",
        ServerPacket::ObjectRangeAttack { .. } => "ObjectRangeAttack",
        ServerPacket::AddBuff { .. } => "AddBuff",
        ServerPacket::RemoveBuff { .. } => "RemoveBuff",
        ServerPacket::PauseBuff { .. } => "PauseBuff",
        ServerPacket::ObjectHidden { .. } => "ObjectHidden",
        ServerPacket::RefreshItem { .. } => "RefreshItem",
        ServerPacket::ObjectSpell { .. } => "ObjectSpell",
        ServerPacket::UserDash { .. } => "UserDash",
        ServerPacket::ObjectDash { .. } => "ObjectDash",
        ServerPacket::UserDashFail { .. } => "UserDashFail",
        ServerPacket::ObjectDashFail { .. } => "ObjectDashFail",
        ServerPacket::ConsignItem { .. } => "ConsignItem",
        ServerPacket::MarketFail { .. } => "MarketFail",
        ServerPacket::MarketSuccess { .. } => "MarketSuccess",
        ServerPacket::HeroCreateRequest { .. } => "HeroCreateRequest",
        ServerPacket::NewHero { .. } => "NewHero",
        ServerPacket::UpdateHeroSpawnState { .. } => "UpdateHeroSpawnState",
        ServerPacket::UnlockHeroAutoPot => "UnlockHeroAutoPot",
        ServerPacket::SetHeroBehaviour { .. } => "SetHeroBehaviour",
        ServerPacket::ManageHeroes { .. } => "ManageHeroes",
        ServerPacket::ChangeHero { .. } => "ChangeHero",
        ServerPacket::DefaultNPC { .. } => "DefaultNPC",
        ServerPacket::NPCUpdate { .. } => "NPCUpdate",
        ServerPacket::MarriageRequest { .. } => "MarriageRequest",
        ServerPacket::DivorceRequest { .. } => "DivorceRequest",
        ServerPacket::MentorRequest { .. } => "MentorRequest",
        ServerPacket::DepositTradeItem { .. } => "DepositTradeItem",
        ServerPacket::RetrieveTradeItem { .. } => "RetrieveTradeItem",
        ServerPacket::TradeRequest { .. } => "TradeRequest",
        ServerPacket::TradeAccept { .. } => "TradeAccept",
        ServerPacket::TradeGold { .. } => "TradeGold",
        ServerPacket::TradeItem { .. } => "TradeItem",
        ServerPacket::TradeConfirm => "TradeConfirm",
        ServerPacket::TradeCancel { .. } => "TradeCancel",
        ServerPacket::MountUpdate { .. } => "MountUpdate",
        ServerPacket::FishingUpdate { .. } => "FishingUpdate",
        ServerPacket::RemoveDelayedExplosion { .. } => "RemoveDelayedExplosion",
        ServerPacket::ObjectDeco { .. } => "ObjectDeco",
        ServerPacket::ObjectSneaking { .. } => "ObjectSneaking",
        ServerPacket::ObjectLevelEffects { .. } => "ObjectLevelEffects",
        ServerPacket::SetBindingShot { .. } => "SetBindingShot",
        ServerPacket::SendOutputMessage { .. } => "SendOutputMessage",
        ServerPacket::OpenDoor { .. } => "Opendoor",
        ServerPacket::OpenBrowser { .. } => "OpenBrowser",
        ServerPacket::PlaySound { .. } => "PlaySound",
        ServerPacket::SetTimer { .. } => "SetTimer",
        ServerPacket::ExpireTimer { .. } => "ExpireTimer",
        ServerPacket::Roll { .. } => "Roll",
        ServerPacket::SetCompass { .. } => "SetCompass",
        ServerPacket::NPCAwakening => "NPCAwakening",
        ServerPacket::NPCDisassemble => "NPCDisassemble",
        ServerPacket::NPCDowngrade => "NPCDowngrade",
        ServerPacket::NPCReset => "NPCReset",
        ServerPacket::AwakeningLockedItem { .. } => "AwakeningLockedItem",
        ServerPacket::Awakening { .. } => "Awakening",
        ServerPacket::ReceiveMail { .. } => "ReceiveMail",
        ServerPacket::MailLockedItem { .. } => "MailLockedItem",
        ServerPacket::MailSendRequest => "MailSendRequest",
        ServerPacket::MailSent { .. } => "MailSent",
        ServerPacket::ParcelCollected { .. } => "ParcelCollected",
        ServerPacket::MailCost { .. } => "MailCost",
        ServerPacket::FriendUpdate { .. } => "FriendUpdate",
        ServerPacket::LoverUpdate { .. } => "LoverUpdate",
        ServerPacket::MentorUpdate { .. } => "MentorUpdate",
        ServerPacket::GuildBuffList { .. } => "GuildBuffList",
        ServerPacket::GameShopInfo { .. } => "GameShopInfo",
        ServerPacket::NewIntelligentCreature { .. } => "NewIntelligentCreature",
        ServerPacket::UpdateIntelligentCreatureList { .. } => "UpdateIntelligentCreatureList",
        ServerPacket::IntelligentCreatureEnableRename => "IntelligentCreatureEnableRename",
        ServerPacket::IntelligentCreaturePickup { .. } => "IntelligentCreaturePickup",
        ServerPacket::GetRentedItems { .. } => "GetRentedItems",
        ServerPacket::ItemRentalRequest { .. } => "ItemRentalRequest",
        ServerPacket::ItemRentalFee { .. } => "ItemRentalFee",
        ServerPacket::ItemRentalPeriod { .. } => "ItemRentalPeriod",
        ServerPacket::DepositRentalItem { .. } => "DepositRentalItem",
        ServerPacket::RetrieveRentalItem { .. } => "RetrieveRentalItem",
        ServerPacket::UpdateRentalItem { .. } => "UpdateRentalItem",
        ServerPacket::CancelItemRental => "CancelItemRental",
        ServerPacket::ItemRentalLock { .. } => "ItemRentalLock",
        ServerPacket::ItemRentalPartnerLock { .. } => "ItemRentalPartnerLock",
        ServerPacket::CanConfirmItemRental => "CanConfirmItemRental",
        ServerPacket::ConfirmItemRental => "ConfirmItemRental",
        ServerPacket::ChangeQuest { .. } => "ChangeQuest",
        ServerPacket::CompleteQuest { .. } => "CompleteQuest",
        ServerPacket::ShareQuest { .. } => "ShareQuest",
        ServerPacket::NewQuestInfo { .. } => "NewQuestInfo",
        ServerPacket::NewRecipeInfo { .. } => "NewRecipeInfo",
        ServerPacket::ResizeInventory { .. } => "ResizeInventory",
        ServerPacket::ResizeStorage { .. } => "ResizeStorage",
        ServerPacket::StorageUnlockResult { .. } => "StorageUnlockResult",
        ServerPacket::StoragePasswordResult { .. } => "StoragePasswordResult",
        ServerPacket::LogOutSuccess { .. } => "LogOutSuccess",
        ServerPacket::LogOutFailed => "LogOutFailed",
        other => server_packet_raw_name(other.packet_id()),
    }
}
