// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module mir2_mine::stones_left {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::DappStorage;
    use dubhe::dapp_system;
    use mir2_mine::dapp_key;
    use mir2_mine::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"stones_left";
    const OFFCHAIN: bool = false;

    public fun has(dapp_storage: &DappStorage, mine_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        dapp_system::has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has(dapp_storage: &DappStorage, mine_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        dapp_system::ensure_has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has_not(dapp_storage: &DappStorage, mine_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        dapp_system::ensure_has_not_global_record<DappKey>(dapp_storage, key_tuple)
    }
  

    public(package) fun delete(dapp_storage: &mut DappStorage, mine_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        dapp_system::delete_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, vector[b"stones"]);
    }

    public fun get(dapp_storage: &DappStorage, mine_id: u64): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let stones_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"stones");
        let mut stones_bcs = sui::bcs::new(stones_raw);
        let value = sui::bcs::peel_u32(&mut stones_bcs);
        value
    }

    public(package) fun set(dapp_storage: &mut DappStorage, mine_id: u64, value: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let field_names = vector[b"stones"];
        let value_tuple = encode(value);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun encode(value: u32): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&value));
        value_tuple
    }
}