  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module mir2_mine::mir2_mine_schema {

  use std::ascii::String;

  use std::ascii::string;

  use sui::package::UpgradeCap;

  use std::type_name;

  use dubhe::storage;

  use dubhe::storage_value::{Self, StorageValue};

  use dubhe::storage_map::{Self, StorageMap};

  use dubhe::storage_double_map::{Self, StorageDoubleMap};

  use sui::dynamic_field as df;

  use mir2_mine::mir2_mine_dapp_metadata::DappMetadata;

  use mir2_mine::mir2_mine_ore_kind::OreKind;

  use mir2_mine::mir2_mine_mine_config::MineConfig;

  public struct Schema has key, store {
    id: UID,
  }

  // Default storage

  public fun borrow_dapp__admin(self: &Schema): &StorageValue<address> {
    storage::borrow_field(&self.id, b"dapp__admin")
  }

  public fun borrow_dapp__package_id(self: &Schema): &StorageValue<address> {
    storage::borrow_field(&self.id, b"dapp__package_id")
  }

  public fun borrow_dapp__version(self: &Schema): &StorageValue<u32> {
    storage::borrow_field(&self.id, b"dapp__version")
  }

  public fun borrow_dapp__metadata(self: &Schema): &StorageValue<DappMetadata> {
    storage::borrow_field(&self.id, b"dapp__metadata")
  }

  public fun borrow_dapp__safe_mode(self: &Schema): &StorageValue<bool> {
    storage::borrow_field(&self.id, b"dapp__safe_mode")
  }

  public fun borrow_dapp__authorised_schemas(self: &Schema): &StorageValue<vector<address>> {
    storage::borrow_field(&self.id, b"dapp__authorised_schemas")
  }

  public fun borrow_dapp__schemas(self: &Schema): &StorageValue<vector<address>> {
    storage::borrow_field(&self.id, b"dapp__schemas")
  }

  public(package) fun dapp__admin(self: &mut Schema): &mut StorageValue<address> {
    storage::borrow_mut_field(&mut self.id, b"dapp__admin")
  }

  public(package) fun dapp__package_id(self: &mut Schema): &mut StorageValue<address> {
    storage::borrow_mut_field(&mut self.id, b"dapp__package_id")
  }

  public(package) fun dapp__version(self: &mut Schema): &mut StorageValue<u32> {
    storage::borrow_mut_field(&mut self.id, b"dapp__version")
  }

  public(package) fun dapp__metadata(self: &mut Schema): &mut StorageValue<DappMetadata> {
    storage::borrow_mut_field(&mut self.id, b"dapp__metadata")
  }

  public(package) fun dapp__safe_mode(self: &mut Schema): &mut StorageValue<bool> {
    storage::borrow_mut_field(&mut self.id, b"dapp__safe_mode")
  }

  public(package) fun dapp__authorised_schemas(self: &mut Schema): &mut StorageValue<vector<address>> {
    storage::borrow_mut_field(&mut self.id, b"dapp__authorised_schemas")
  }

  public fun borrow_config(self: &Schema): &StorageMap<u64, MineConfig> {
    storage::borrow_field(&self.id, b"config")
  }

  public(package) fun config(self: &mut Schema): &mut StorageMap<u64, MineConfig> {
    storage::borrow_mut_field(&mut self.id, b"config")
  }

  public fun borrow_stones_left(self: &Schema): &StorageMap<u64, u32> {
    storage::borrow_field(&self.id, b"stones_left")
  }

  public(package) fun stones_left(self: &mut Schema): &mut StorageMap<u64, u32> {
    storage::borrow_mut_field(&mut self.id, b"stones_left")
  }

  public fun borrow_next_regen_ms(self: &Schema): &StorageMap<u64, u64> {
    storage::borrow_field(&self.id, b"next_regen_ms")
  }

  public(package) fun next_regen_ms(self: &mut Schema): &mut StorageMap<u64, u64> {
    storage::borrow_mut_field(&mut self.id, b"next_regen_ms")
  }

  public fun borrow_ore_balance(self: &Schema): &StorageDoubleMap<address, OreKind, u64> {
    storage::borrow_field(&self.id, b"ore_balance")
  }

  public(package) fun ore_balance(self: &mut Schema): &mut StorageDoubleMap<address, OreKind, u64> {
    storage::borrow_mut_field(&mut self.id, b"ore_balance")
  }

  public fun borrow_miner_nonce(self: &Schema): &StorageMap<address, u64> {
    storage::borrow_field(&self.id, b"miner_nonce")
  }

  public(package) fun miner_nonce(self: &mut Schema): &mut StorageMap<address, u64> {
    storage::borrow_mut_field(&mut self.id, b"miner_nonce")
  }

  public fun borrow_emitted_this_epoch(self: &Schema): &StorageValue<u64> {
    storage::borrow_field(&self.id, b"emitted_this_epoch")
  }

  public(package) fun emitted_this_epoch(self: &mut Schema): &mut StorageValue<u64> {
    storage::borrow_mut_field(&mut self.id, b"emitted_this_epoch")
  }

  public fun borrow_treasury_mist(self: &Schema): &StorageValue<u64> {
    storage::borrow_field(&self.id, b"treasury_mist")
  }

  public(package) fun treasury_mist(self: &mut Schema): &mut StorageValue<u64> {
    storage::borrow_mut_field(&mut self.id, b"treasury_mist")
  }

  public fun borrow_treasury_addr(self: &Schema): &StorageValue<address> {
    storage::borrow_field(&self.id, b"treasury_addr")
  }

  public(package) fun treasury_addr(self: &mut Schema): &mut StorageValue<address> {
    storage::borrow_mut_field(&mut self.id, b"treasury_addr")
  }

  public fun borrow_per_swing_fee(self: &Schema): &StorageValue<u64> {
    storage::borrow_field(&self.id, b"per_swing_fee")
  }

  public(package) fun per_swing_fee(self: &mut Schema): &mut StorageValue<u64> {
    storage::borrow_mut_field(&mut self.id, b"per_swing_fee")
  }

  public fun borrow_epoch_emission_cap(self: &Schema): &StorageValue<u64> {
    storage::borrow_field(&self.id, b"epoch_emission_cap")
  }

  public(package) fun epoch_emission_cap(self: &mut Schema): &mut StorageValue<u64> {
    storage::borrow_mut_field(&mut self.id, b"epoch_emission_cap")
  }

  public(package) fun create(ctx: &mut TxContext): Schema {
    let mut id = object::new(ctx);
    storage::add_field<StorageMap<u64, MineConfig>>(&mut id, b"config", storage_map::new(b"config", ctx));
    storage::add_field<StorageMap<u64, u32>>(&mut id, b"stones_left", storage_map::new(b"stones_left", ctx));
    storage::add_field<StorageMap<u64, u64>>(&mut id, b"next_regen_ms", storage_map::new(b"next_regen_ms", ctx));
    storage::add_field<StorageDoubleMap<address, OreKind, u64>>(&mut id, b"ore_balance", storage_double_map::new(b"ore_balance", ctx));
    storage::add_field<StorageMap<address, u64>>(&mut id, b"miner_nonce", storage_map::new(b"miner_nonce", ctx));
    storage::add_field<StorageValue<u64>>(&mut id, b"emitted_this_epoch", storage_value::new(b"emitted_this_epoch", ctx));
    storage::add_field<StorageValue<u64>>(&mut id, b"treasury_mist", storage_value::new(b"treasury_mist", ctx));
    storage::add_field<StorageValue<address>>(&mut id, b"treasury_addr", storage_value::new(b"treasury_addr", ctx));
    storage::add_field<StorageValue<u64>>(&mut id, b"per_swing_fee", storage_value::new(b"per_swing_fee", ctx));
    storage::add_field<StorageValue<u64>>(&mut id, b"epoch_emission_cap", storage_value::new(b"epoch_emission_cap", ctx));
    Schema { id }
  }

  public(package) fun id(self: &mut Schema): &mut UID {
    &mut self.id
  }

  public(package) fun borrow_id(self: &Schema): &UID {
    &self.id
  }

  public fun migrate(_schema: &mut Schema, _ctx: &mut TxContext) {}

  public(package) fun upgrade(schema: &mut Schema, new_package_id: address, new_version: u32, ctx: &mut TxContext) {
    assert!(schema.dapp__metadata().contains(), 0);
    assert!(schema.dapp__admin().get() == ctx.sender(), 0);
    schema.dapp__package_id().set(new_package_id);
    let current_version = schema.dapp__version()[];
    assert!(current_version < new_version, 0);
    schema.dapp__version().set(new_version);
    schema.migrate(ctx);
  }

  // ======================================== View Functions ========================================

  public fun get_config(self: &Schema, key: u64): &MineConfig {
    self.borrow_config().get(key)
  }

  public fun get_stones_left(self: &Schema, key: u64): &u32 {
    self.borrow_stones_left().get(key)
  }

  public fun get_next_regen_ms(self: &Schema, key: u64): &u64 {
    self.borrow_next_regen_ms().get(key)
  }

  public fun get_ore_balance(self: &Schema, key1: address, key2: OreKind): &u64 {
    self.borrow_ore_balance().get(key1, key2)
  }

  public fun get_miner_nonce(self: &Schema, key: address): &u64 {
    self.borrow_miner_nonce().get(key)
  }

  public fun get_emitted_this_epoch(self: &Schema): &u64 {
    self.borrow_emitted_this_epoch().get()
  }

  public fun get_treasury_mist(self: &Schema): &u64 {
    self.borrow_treasury_mist().get()
  }

  public fun get_treasury_addr(self: &Schema): &address {
    self.borrow_treasury_addr().get()
  }

  public fun get_per_swing_fee(self: &Schema): &u64 {
    self.borrow_per_swing_fee().get()
  }

  public fun get_epoch_emission_cap(self: &Schema): &u64 {
    self.borrow_epoch_emission_cap().get()
  }

  // =========================================================================================================
}
