// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module mir2_mine::ore_kind {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum OreKind has copy, drop, store {
        Amethyst,BlackIron,Copper,Gold,Nephrite,Platinum,Ruby,Silver
    }

    public fun new_amethyst(): OreKind {
        OreKind::Amethyst
    }

    public fun new_blackiron(): OreKind {
        OreKind::BlackIron
    }

    public fun new_copper(): OreKind {
        OreKind::Copper
    }

    public fun new_gold(): OreKind {
        OreKind::Gold
    }

    public fun new_nephrite(): OreKind {
        OreKind::Nephrite
    }

    public fun new_platinum(): OreKind {
        OreKind::Platinum
    }

    public fun new_ruby(): OreKind {
        OreKind::Ruby
    }

    public fun new_silver(): OreKind {
        OreKind::Silver
    }

    public fun encode(self: OreKind): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): OreKind {
        match(peel_enum_tag(bytes)) {
            0 => OreKind::Amethyst,
            1 => OreKind::BlackIron,
            2 => OreKind::Copper,
            3 => OreKind::Gold,
            4 => OreKind::Nephrite,
            5 => OreKind::Platinum,
            6 => OreKind::Ruby,
            7 => OreKind::Silver,
            _ => abort,
        }
    }
}