/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const getMir2RendererBackend: () => [number, number];
export const pushMir2MovementShadowEvent: (a: number, b: number) => void;
export const getMir2MovementShadowDiagnostics: () => [number, number];
export const setMir2RemoteMotionPresentationEnabled: (a: number) => void;
export const getMir2RemoteMotionPresentationDiagnostics: () => [number, number];
export const getMir2LocalMotionDiagnostics: () => [number, number];
export const setMir2LocalMotionPresentationEnabled: (a: number) => void;
export const getMir2PresentationPoses: () => [number, number];
export const setMir2PresentationPoseEnabled: (a: number) => void;
export const setMir2WorldState: (a: number, b: number) => void;
export const setMir2EntityRenderState: (a: number, b: number) => void;
export const setMir2EntityRenderAtlas: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const setMir2MapRenderState: (a: number, b: number) => void;
export const setMir2MapRenderAtlas: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const evictMir2MapRenderImages: (a: number, b: number) => void;
export const bootMir2Runtime: () => void;
export const setMir2SelfCameraMotion: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const setMir2PresentationPoseSink: (a: any) => void;
export const setMir2MapCameraOffset: (a: number, b: number) => void;
export const setMir2StatusSink: (a: any) => void;
export const releaseMir2MapRenderImages: (a: number, b: number) => void;
export const clearMir2StatusSink: () => void;
export const clearMir2PresentationPoseSink: () => void;
export const wasm_bindgen__convert__closures_____invoke__h4a292f8eb4388d53: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h8f94c947f52443eb: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h32082366a76e6c6b: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h32082366a76e6c6b_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h32082366a76e6c6b_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h32082366a76e6c6b_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h32082366a76e6c6b_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h32082366a76e6c6b_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h32082366a76e6c6b_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h32082366a76e6c6b_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hcfe12d7fe9aa4faf: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
