  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module mir2_mine::mir2_mine_mine_settled_event {

  use sui::event;

  use std::ascii::String;

  use mir2_mine::mir2_mine_ore_kind::OreKind;

  use mir2_mine::mir2_mine_mine_config::MineConfig;

  public struct MineSettledEvent has copy, drop {
    miner: address,
    mine_id: u64,
    swings: u64,
    ore_kind: OreKind,
    ore_amount: u64,
    stones_left: u32,
    fee_paid: u64,
    nonce: u64,
  }

  public fun new(
    miner: address,
    mine_id: u64,
    swings: u64,
    ore_kind: OreKind,
    ore_amount: u64,
    stones_left: u32,
    fee_paid: u64,
    nonce: u64,
  ): MineSettledEvent {
    MineSettledEvent {
                                   miner,mine_id,swings,ore_kind,ore_amount,stones_left,fee_paid,nonce
                               }
  }
}
