  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module mir2_mine::mir2_mine_mine_depleted_event {

  use sui::event;

  use std::ascii::String;

  use mir2_mine::mir2_mine_ore_kind::OreKind;

  use mir2_mine::mir2_mine_mine_config::MineConfig;

  public struct MineDepletedEvent has copy, drop {
    mine_id: u64,
  }

  public fun new(mine_id: u64): MineDepletedEvent {
    MineDepletedEvent {
                                   mine_id
                               }
  }
}
