  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module mir2_mine::mir2_mine_mine_config {

  use std::ascii::String;

  public struct MineConfig has copy, drop, store {
    map_id: u32,
    mine_set: u8,
    max_stones: u32,
    regen_secs: u32,
    hit_rate: u8,
    drop_rate: u8,
  }

  public fun new(map_id: u32, mine_set: u8, max_stones: u32, regen_secs: u32, hit_rate: u8, drop_rate: u8): MineConfig {
    MineConfig {
                                   map_id,mine_set,max_stones,regen_secs,hit_rate,drop_rate
                               }
  }

  public fun get(self: &MineConfig): (u32,u8,u32,u32,u8,u8) {
    (self.map_id,self.mine_set,self.max_stones,self.regen_secs,self.hit_rate,self.drop_rate)
  }

  public fun get_map_id(self: &MineConfig): u32 {
    self.map_id
  }

  public fun get_mine_set(self: &MineConfig): u8 {
    self.mine_set
  }

  public fun get_max_stones(self: &MineConfig): u32 {
    self.max_stones
  }

  public fun get_regen_secs(self: &MineConfig): u32 {
    self.regen_secs
  }

  public fun get_hit_rate(self: &MineConfig): u8 {
    self.hit_rate
  }

  public fun get_drop_rate(self: &MineConfig): u8 {
    self.drop_rate
  }

  public(package) fun set_map_id(self: &mut MineConfig, map_id: u32) {
    self.map_id = map_id;
  }

  public(package) fun set_mine_set(self: &mut MineConfig, mine_set: u8) {
    self.mine_set = mine_set;
  }

  public(package) fun set_max_stones(self: &mut MineConfig, max_stones: u32) {
    self.max_stones = max_stones;
  }

  public(package) fun set_regen_secs(self: &mut MineConfig, regen_secs: u32) {
    self.regen_secs = regen_secs;
  }

  public(package) fun set_hit_rate(self: &mut MineConfig, hit_rate: u8) {
    self.hit_rate = hit_rate;
  }

  public(package) fun set_drop_rate(self: &mut MineConfig, drop_rate: u8) {
    self.drop_rate = drop_rate;
  }

  public(package) fun set(
    self: &mut MineConfig,
    map_id: u32,
    mine_set: u8,
    max_stones: u32,
    regen_secs: u32,
    hit_rate: u8,
    drop_rate: u8,
  ) {
    self.map_id = map_id;
    self.mine_set = mine_set;
    self.max_stones = max_stones;
    self.regen_secs = regen_secs;
    self.hit_rate = hit_rate;
    self.drop_rate = drop_rate;
  }
}
