  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module mir2_mine::mir2_mine_ore_kind {

  public enum OreKind has copy, drop , store {
                                Amethyst,BlackIron,Copper,Gold,Nephrite,Platinum,Ruby,Silver
                        }

  public fun new_amethyst(): OreKind {
    OreKind::Amethyst
  }

  public fun new_black_iron(): OreKind {
    OreKind::BlackIron
  }

  public fun new_copper(): OreKind {
    OreKind::Copper
  }

  public fun new_gold(): OreKind {
    OreKind::Gold
  }

  public fun new_nephrite(): OreKind {
    OreKind::Nephrite
  }

  public fun new_platinum(): OreKind {
    OreKind::Platinum
  }

  public fun new_ruby(): OreKind {
    OreKind::Ruby
  }

  public fun new_silver(): OreKind {
    OreKind::Silver
  }
}
