  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module mir2_mine::mir2_mine_ore_redeemed_event {

  use sui::event;

  use std::ascii::String;

  use mir2_mine::mir2_mine_ore_kind::OreKind;

  use mir2_mine::mir2_mine_mine_config::MineConfig;

  public struct OreRedeemedEvent has copy, drop {
    miner: address,
    ore_kind: OreKind,
    amount: u64,
  }

  public fun new(miner: address, ore_kind: OreKind, amount: u64): OreRedeemedEvent {
    OreRedeemedEvent {
                                   miner,ore_kind,amount
                               }
  }
}
