  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module mir2_mine::mir2_mine_errors {

  #[error]

  const MINENOTFOUND: vector<u8> = b"Mine not found";

  public fun MineNotFound_error(condition: bool) {
    assert!(condition, MINENOTFOUND)
  }

  #[error]

  const MINEEXHAUSTED: vector<u8> = b"Mine has no stones left";

  public fun MineExhausted_error(condition: bool) {
    assert!(condition, MINEEXHAUSTED)
  }

  #[error]

  const BADNONCE: vector<u8> = b"Replay or out-of-order nonce";

  public fun BadNonce_error(condition: bool) {
    assert!(condition, BADNONCE)
  }

  #[error]

  const INSUFFICIENTFEE: vector<u8> = b"Attached SUI is less than the required fee";

  public fun InsufficientFee_error(condition: bool) {
    assert!(condition, INSUFFICIENTFEE)
  }

  #[error]

  const EMISSIONCAPREACHED: vector<u8> = b"Epoch emission cap reached";

  public fun EmissionCapReached_error(condition: bool) {
    assert!(condition, EMISSIONCAPREACHED)
  }

  #[error]

  const NOTADMIN: vector<u8> = b"Caller does not hold the admin capability";

  public fun NotAdmin_error(condition: bool) {
    assert!(condition, NOTADMIN)
  }

  #[error]

  const BADSWINGS: vector<u8> = b"Swings must be greater than zero";

  public fun BadSwings_error(condition: bool) {
    assert!(condition, BADSWINGS)
  }

  #[error]

  const INSUFFICIENTORE: vector<u8> = b"Insufficient ore balance to redeem";

  public fun InsufficientOre_error(condition: bool) {
    assert!(condition, INSUFFICIENTORE)
  }

  #[error]

  const BADAMOUNT: vector<u8> = b"Amount must be greater than zero";

  public fun BadAmount_error(condition: bool) {
    assert!(condition, BADAMOUNT)
  }
}
