  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module mir2_mine::mir2_mine_events {

  use std::ascii::{String, string};

  use mir2_mine::mir2_mine_ore_kind::OreKind;

  use mir2_mine::mir2_mine_mine_config::MineConfig;

  use mir2_mine::mir2_mine_mine_settled_event::MineSettledEvent;

  use mir2_mine::mir2_mine_mine_settled_event;

  public fun mine_settled_event(
    miner: address,
    mine_id: u64,
    swings: u64,
    ore_kind: OreKind,
    ore_amount: u64,
    stones_left: u32,
    fee_paid: u64,
    nonce: u64,
  ) {
    dubhe::storage_event::emit_set_record<MineSettledEvent, MineSettledEvent, MineSettledEvent>(
				string(b"mine_settled_event"),
				option::none(),
			  	option::none(),
			  option::some(mir2_mine_mine_settled_event::new(miner,mine_id,swings,ore_kind,ore_amount,stones_left,fee_paid,nonce))
			  )
  }

  use mir2_mine::mir2_mine_mine_depleted_event::MineDepletedEvent;

  use mir2_mine::mir2_mine_mine_depleted_event;

  public fun mine_depleted_event(mine_id: u64) {
    dubhe::storage_event::emit_set_record<MineDepletedEvent, MineDepletedEvent, MineDepletedEvent>(
				string(b"mine_depleted_event"),
				option::none(),
			  	option::none(),
			  option::some(mir2_mine_mine_depleted_event::new(mine_id))
			  )
  }

  use mir2_mine::mir2_mine_mine_regened_event::MineRegenedEvent;

  use mir2_mine::mir2_mine_mine_regened_event;

  public fun mine_regened_event(mine_id: u64, stones_left: u32) {
    dubhe::storage_event::emit_set_record<MineRegenedEvent, MineRegenedEvent, MineRegenedEvent>(
				string(b"mine_regened_event"),
				option::none(),
			  	option::none(),
			  option::some(mir2_mine_mine_regened_event::new(mine_id,stones_left))
			  )
  }

  use mir2_mine::mir2_mine_ore_redeemed_event::OreRedeemedEvent;

  use mir2_mine::mir2_mine_ore_redeemed_event;

  public fun ore_redeemed_event(miner: address, ore_kind: OreKind, amount: u64) {
    dubhe::storage_event::emit_set_record<OreRedeemedEvent, OreRedeemedEvent, OreRedeemedEvent>(
				string(b"ore_redeemed_event"),
				option::none(),
			  	option::none(),
			  option::some(mir2_mine_ore_redeemed_event::new(miner,ore_kind,amount))
			  )
  }
}
