port 26379
dir /tmp
protected-mode no
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor mir2-primary redis-primary 6379 2
sentinel down-after-milliseconds mir2-primary 1000
sentinel failover-timeout mir2-primary 5000
sentinel parallel-syncs mir2-primary 1
