import {burnSpellsRun,sameSpellsOwner,type SpellsOwner} from "./bevy-spells-ui";
import type { CrystalKeyBinding } from "./player-ui-preferences";
export type CombatOwner=SpellsOwner;
export type CombatUiChannel="bag"|"character"|"hud"|"spells"|"storage"|"npcShop";
export type CombatIdentity=CombatOwner&{controllerRun:number};
export type CombatActor={objectId:string;kind:"selfPlayer"|"player"|"monster"|"npc";x:number;y:number;direction:string|null;dead:boolean;masterObjectId:number;ai:number};
export type CombatFacts={map:string;enabled:boolean;player:CombatActor;hp:number;maxHp:number;mp:number;level:number;attackSpeed:number;actors:CombatActor[];clickTargets:Array<{kind:CombatActor["kind"];objectId:number;x:number;y:number;dead:boolean|null;ai:number|null;harvestable:boolean|null}>;selectedObjectId:number|null;hoveredObjectId:string|null;cursor:[number,number]|null;class:string|null;hasClassWeapon:boolean|null;ridingMount:boolean|null;fishing:boolean|null;dazed:boolean|null;motionRemainingMs:number;movementReady:boolean;planningPosition:[number,number]|null;neighbours:Array<{x:number;y:number;cost:number}>;spellLockKey:string;pointerSpellLock:boolean;bindings:readonly CrystalKeyBinding[]|null};
export type CombatCommand={type:string;[field:string]:unknown};
export type CombatProof={identity:CombatIdentity;modelRevision:number;map:string;sequence:number;edgeSequence:number;movementBlockMs:number;slot:number|null;skillId:number|null;spell:string|null;targetId:number|null;command:CombatCommand};
export type CombatAction={type:"key";key:string;repeat?:boolean;modifiers:{alt:boolean;ctrl:boolean;shift:boolean;tilde:boolean}}|{type:"skillKey";skillKey:string}|{type:"slot";slot:number;cursor:[number,number]|null}|{type:"select";objectId:number}|{type:"cancel"};
export type CombatRuntime={getMir2CombatInputCapabilities?:()=>string;setMir2CombatInputSnapshot?:(json:string)=>boolean;setMir2CombatInputEdge?:(json:string)=>string;getMir2CombatInputStatus?:()=>string;setMir2CombatInputIntentSink?:(sink:(json:string)=>string)=>void;clearMir2CombatInputIntentSink?:()=>void;withdrawMir2CombatInputSnapshot?:(json:string)=>void};
type Timing={spell:string;sequence:number;observedAtMs:number;delayMs:number|null};
type Status={version:1;frame:number;ready:boolean;identity:CombatIdentity|null;modelRevision:number|null;revision:number|null;map:string|null};
export type CombatRaw={playerObjectId:number|null;knownSkills:unknown};
type Snapshot=CombatFacts&{identity:CombatIdentity;revision:number;modelRevision:number;nowMs:number;learned:unknown[];timing:Timing[]};
type Options={runtime:CombatRuntime;isCurrent:()=>boolean;read:()=>{owner:CombatOwner|null;facts:CombatFacts|null};now:()=>number;onReady:(ready:boolean)=>void;onWire:(proof:CombatProof,serialized:string)=>"confirmedSend"|"definitelyUnsent"|"outcomeUnknown";onApproach:(x:number,y:number)=>void;onClear:()=>void};
const safe=(v:unknown):v is number=>Number.isSafeInteger(v)&&Number(v)>=0;
const object=(v:unknown):v is Record<string,unknown>=>Boolean(v)&&typeof v==="object"&&!Array.isArray(v);
const ownerKeys=["connectionGeneration","sessionGeneration","ownerRevision","playerObjectId"] as const;
function validOwner(v:unknown):v is CombatOwner {return object(v)&&ownerKeys.every(k=>safe(v[k]))&&Number(v.connectionGeneration)>0&&Number(v.sessionGeneration)>0&&Number(v.playerObjectId)>0&&Number(v.playerObjectId)<=0xffffffff;}
function validIdentity(v:unknown):v is CombatIdentity {const run=(v as CombatIdentity|null)?.controllerRun;return validOwner(v)&&safe(run)&&run>=1&&run<2**31&&Object.keys(v).sort().join()===[...ownerKeys,"controllerRun"].sort().join();}
function sameIdentity(a:CombatIdentity,b:CombatIdentity){return a.controllerRun===b.controllerRun&&sameSpellsOwner(a,b);}
function owners(){const realm=globalThis as typeof globalThis&{__mir2CombatRuntimeOwnersV1?:WeakMap<object,number>};return realm.__mir2CombatRuntimeOwnersV1??=new WeakMap();}
export function supportsCombat(r:CombatRuntime|null){try{const c=JSON.parse(r?.getMir2CombatInputCapabilities?.()??"null");return object(c)&&Object.keys(c).sort().join()==="combatInputAbiVersion,combatIntentAbiVersion,compiled,schemaVersion,startup"&&c.schemaVersion===1&&c.combatInputAbiVersion===1&&c.combatIntentAbiVersion===1&&c.compiled===true&&typeof c.startup==="boolean"&&[r?.setMir2CombatInputSnapshot,r?.setMir2CombatInputEdge,r?.getMir2CombatInputStatus,r?.setMir2CombatInputIntentSink,r?.clearMir2CombatInputIntentSink,r?.withdrawMir2CombatInputSnapshot].every(f=>typeof f==="function");}catch{return false;}}
function status(r:CombatRuntime):Status|null {try{const v:unknown=JSON.parse(r.getMir2CombatInputStatus?.()??"null");if(!object(v)||v.version!==1||!safe(v.frame)||typeof v.ready!=="boolean"||!(v.identity===null||validIdentity(v.identity))||![v.modelRevision,v.revision].every(n=>n===null||safe(n))||!(v.map===null||typeof v.map==="string"))return null;return v as Status;}catch{return null;}}
function wire(v:unknown):v is CombatCommand {if(!object(v)||typeof v.type!=="string")return false;const keys:Record<string,string[]>={attack:["objectId"],attackDirection:["direction","spell"],rangeAttack:["direction","x","y","targetId","targetX","targetY"],harvest:["direction"],magic:["objectId","spell","direction","targetId","x","y","spellTargetLock"],spellToggle:["spell","toggleState"]};const required=keys[v.type];if(!required||Object.keys(v).sort().join()!==["type",...required].sort().join())return false;
 const u32=(n:unknown)=>safe(n)&&n<=0xffffffff,coord=(n:unknown)=>Number.isInteger(n)&&Number(n)>=-2147483648&&Number(n)<=2147483647;
 if("direction"in v&&(typeof v.direction!=="string"||!["up","upright","right","downright","down","downleft","left","upleft"].includes(v.direction)))return false;
 if(["x","y","targetX","targetY"].some(k=>k in v&&!coord(v[k])))return false;
 if("objectId"in v&&(!u32(v.objectId)||v.objectId===0)||"targetId"in v&&!u32(v.targetId))return false;
 if(v.type==="attackDirection")return v.spell===null||safe(v.spell)&&v.spell<=255;
 if(v.type==="magic"||v.type==="spellToggle"){if(typeof v.spell!=="string"||!v.spell.trim()||v.spell.length>128)return false;return v.type==="magic"?typeof v.spellTargetLock==="boolean":v.toggleState===0||v.toggleState===1;}
 return true;}
export function parseCombatProof(value:unknown):CombatProof|null {const v=value;if(!object(v)||Object.keys(v).sort().join()!==["identity","modelRevision","map","sequence","edgeSequence","movementBlockMs","slot","skillId","spell","targetId","command"].sort().join()||!validIdentity(v.identity)||!safe(v.modelRevision)||!safe(v.sequence)||v.sequence===0||Math.floor(v.sequence/2**22)!==v.identity.controllerRun||v.sequence%2**22===0||!safe(v.edgeSequence)||!safe(v.movementBlockMs)||v.movementBlockMs>0xffffffff||typeof v.map!=="string"||!v.map||![v.slot,v.skillId,v.targetId].every(n=>n===null||safe(n))||!(v.spell===null||typeof v.spell==="string"&&v.spell.length>0&&v.spell.length<=128)||!wire(v.command))return null;if(v.modelRevision===0||v.map.length>256||Number(v.skillId)>0xffffffff||Number(v.targetId)>0xffffffff)return null;const skill=v.command.type==="magic"||v.command.type==="spellToggle";if(skill?!(safe(v.slot)&&v.slot>=1&&v.slot<=16&&safe(v.skillId)&&typeof v.spell==="string"&&v.command.spell===v.spell):v.slot!==null||v.skillId!==null||v.spell!==null)return null;if(v.command.type==="attack"&&v.command.objectId!==v.targetId||["magic","rangeAttack"].includes(v.command.type)&&v.command.targetId!==v.targetId)return null;return v as CombatProof;}
/** Thin ownership/transport adapter. Every combat rule and aim remains in Rust. */
export class CombatHost {
  run=burnSpellsRun();private stopped=false;private attached=false;private revision=0;private modelRevision=0;private edgeSequence=0;private seenSequence=0;
  private raw:unknown[]|null=null;private rawOwner:CombatOwner|null=null;private sent:Snapshot|null=null;private modelKey="";private timing=new Map<string,Timing>();private castSequence=0;private lastNow=0;
  private uiHolds=new Map<CombatUiChannel,{token:object;owner:CombatOwner}>();
  private active:{proof:CombatProof;body:string;claimed:boolean}|null=null;private frame=-1;private frameAt=0;
  constructor(private options:Options){this.attach();}
  private read(){try{const input=this.options.read();return {owner:input.owner,facts:input.facts};}catch{return {owner:null,facts:null};}}
  supported(){return supportsCombat(this.options.runtime);}
  hasUiHeld(){return this.uiHolds.size>0;}
  private reconcileUiHolds(owner:CombatOwner|null){for(const [channel,held] of this.uiHolds)if(!owner||!sameSpellsOwner(owner,held.owner))this.uiHolds.delete(channel);}
  setUiHeld(channel:CombatUiChannel,token:object,held:boolean){if(this.stopped||!this.owns()||!this.options.isCurrent()||!["bag","character","hud","spells","storage","npcShop"].includes(channel)||!token||typeof token!=="object")return false;if(!held){if(this.uiHolds.get(channel)?.token!==token)return false;this.uiHolds.delete(channel);return true;}const owner=this.read().owner;if(!validOwner(owner))return false;this.uiHolds.set(channel,{token,owner:{...owner}});this.withdraw();return true;}
  clearUiHeld(){this.uiHolds.clear();}
  private owns(){return owners().get(this.options.runtime)===this.run;}
  private attach(){if(this.attached||this.stopped||!this.supported())return;owners().set(this.options.runtime,this.run);try{this.options.runtime.setMir2CombatInputIntentSink?.(json=>this.receive(json));this.attached=true;}catch{this.stop();}}
  private owner(owner:CombatOwner){this.reconcileUiHolds(owner);if(this.rawOwner&&!sameSpellsOwner(this.rawOwner,owner)){this.withdraw();this.raw=null;this.run=burnSpellsRun();this.edgeSequence=0;this.seenSequence=0;this.timing.clear();this.sent=null;this.modelKey="";if(this.attached)owners().set(this.options.runtime,this.run);}this.rawOwner={...owner};}
  observeSnapshot(snapshot:CombatRaw,owner:CombatOwner){if(this.stopped||this.attached&&!this.owns()||!this.options.isCurrent()||!validOwner(owner)||!sameSpellsOwner(owner,this.read().owner??{} as CombatOwner)||snapshot.playerObjectId!==owner.playerObjectId)return false;
    if(!Array.isArray(snapshot.knownSkills)||snapshot.knownSkills.length>512||snapshot.knownSkills.some(row=>!object(row))){this.raw=null;this.withdraw();return false;}
    this.owner(owner);
    try{this.raw=JSON.parse(JSON.stringify(snapshot.knownSkills));}catch{this.raw=null;this.withdraw();return false;}this.rawOwner={...owner};this.tick();return true;
  }
  observePacket(packet:string,payload:Record<string,unknown>,owner:CombatOwner){if(this.stopped||this.attached&&!this.owns()||!validOwner(owner)||!sameSpellsOwner(owner,this.read().owner??{} as CombatOwner)||!this.options.isCurrent())return false;const spell=payload.spell;if(typeof spell!=="string"||!spell||spell.length>128)return false;const at=Math.floor(this.options.now());if(!safe(at))return false;
    if(!["MagicCast","MagicDelay"].includes(packet)||packet==="MagicDelay"&&(!safe(payload.objectId)||payload.objectId===0||payload.objectId!==owner.playerObjectId||!safe(payload.delay)||payload.delay>0xffffffff)||packet==="MagicCast"&&Object.hasOwn(payload,"objectId")&&payload.objectId!==owner.playerObjectId)return false;
    this.owner(owner);
    if(packet==="MagicCast"){if(Object.hasOwn(payload,"objectId")&&payload.objectId!==owner.playerObjectId)return false;if(this.castSequence===Number.MAX_SAFE_INTEGER||this.timing.size>=512&&!this.timing.has(spell)){this.raw=null;this.withdraw();return false;}const old=this.timing.get(spell);this.timing.set(spell,{spell,sequence:++this.castSequence,observedAtMs:at,delayMs:old?.delayMs??null});}
    else if(packet==="MagicDelay"){if(!safe(payload.objectId)||payload.objectId===0||payload.objectId!==owner.playerObjectId||!safe(payload.delay)||payload.delay>0xffffffff)return false;if(this.timing.size>=512&&!this.timing.has(spell))return false;const old=this.timing.get(spell);this.timing.set(spell,old?{...old,delayMs:payload.delay}:{spell,sequence:0,observedAtMs:at,delayMs:payload.delay});}
    else return false;this.tick();return true;
  }
  tick(){const nowValue=this.options.now();if(!Number.isFinite(nowValue)||nowValue<0||nowValue<this.lastNow){this.raw=null;this.withdraw();return;}this.lastNow=nowValue;if(this.stopped||!this.options.isCurrent()){this.withdraw();return;}this.attach();if(!this.attached||!this.owns())return;const live=this.read();this.reconcileUiHolds(live.owner);if(!live.owner||!live.facts||!this.rawOwner||!sameSpellsOwner(live.owner,this.rawOwner)||!this.raw||!live.facts.enabled||this.hasUiHeld()){this.withdraw();return;}
    const key=JSON.stringify({owner:live.owner,facts:live.facts,learned:this.raw,timing:[...this.timing.values()]});if(key!==this.modelKey){if(this.revision===Number.MAX_SAFE_INTEGER||this.modelRevision===Number.MAX_SAFE_INTEGER){this.raw=null;this.withdraw();return;}const sent:Snapshot={...live.facts,identity:{...live.owner,controllerRun:this.run},revision:++this.revision,modelRevision:++this.modelRevision,nowMs:Math.floor(this.options.now()),learned:this.raw,timing:[...this.timing.values()]};try{if(!this.options.runtime.setMir2CombatInputSnapshot?.(JSON.stringify(sent))){this.withdraw();return;}}catch{this.withdraw();return;}this.sent=sent;this.modelKey=key;}
    const s=status(this.options.runtime),now=this.options.now();if(s&&s.frame!==this.frame){this.frame=s.frame;this.frameAt=now;}if(!s?.ready||now-this.frameAt>500){this.withdraw();return;}this.options.onReady(Boolean(this.sent&&s?.ready&&s.identity&&sameIdentity(s.identity,this.sent.identity)&&s.modelRevision===this.sent.modelRevision&&s.map===this.sent.map&&now-this.frameAt<=500));
  }
  fresh(){this.tick();const s=status(this.options.runtime),live=this.read();return Boolean(this.sent&&this.raw&&live.owner&&live.facts?.enabled&&sameSpellsOwner(live.owner,this.sent.identity)&&this.options.isCurrent()&&this.owns()&&s?.ready&&s.identity&&sameIdentity(s.identity,this.sent.identity)&&s.modelRevision===this.sent.modelRevision&&s.map===this.sent.map&&this.options.now()-this.frameAt<=500);}
  edge(action:CombatAction){if(action.type==="cancel")this.active=null;this.tick();if(!this.attached||!this.owns()||this.edgeSequence===Number.MAX_SAFE_INTEGER)return false;const live=this.read();if(!this.sent&&action.type!=="key")return false;const edge={identity:this.sent?.identity??{connectionGeneration:live.owner?.connectionGeneration??0,sessionGeneration:live.owner?.sessionGeneration??0,ownerRevision:live.owner?.ownerRevision??0,playerObjectId:live.owner?.playerObjectId??0,controllerRun:this.run},modelRevision:this.sent?.modelRevision??0,map:this.sent?.map??live.facts?.map??"",sequence:++this.edgeSequence,action};try{return JSON.parse(this.options.runtime.setMir2CombatInputEdge?.(JSON.stringify(edge))??"null")?.handled===true;}catch{return false;}}
  private receive(json:string){let output:unknown;try{output=JSON.parse(json);}catch{return JSON.stringify({outcome:"definitelyUnsent"});}if(!object(output))return JSON.stringify({outcome:"definitelyUnsent"});
    if(output.type==="clear"){if(this.owns()){this.active=null;this.options.onClear();}return "{}";}
    if(output.type==="approach"){if(this.fresh()&&validIdentity(output.identity)&&this.sent&&sameIdentity(output.identity,this.sent.identity)&&output.modelRevision===this.sent.modelRevision&&output.map===this.sent.map&&safe(output.sequence)&&Math.floor(output.sequence/2**22)===this.run&&output.sequence%2**22>0&&output.sequence>this.seenSequence&&safe(output.edgeSequence)&&output.targetId===this.sent.selectedObjectId&&this.sent.actors.some(a=>Number(a.objectId)===output.targetId)&&Number.isInteger(output.x)&&Number.isInteger(output.y)){this.seenSequence=output.sequence;this.options.onApproach(Number(output.x),Number(output.y));}return "{}";}
    const proof=output.type==="wire"?parseCombatProof(output.proof):null;if(!proof||!this.fresh()||proof.sequence<=this.seenSequence)return JSON.stringify({outcome:"definitelyUnsent"});this.seenSequence=proof.sequence;
    const body=JSON.stringify(proof.command);this.active={proof,body,claimed:false};let outcome:"confirmedSend"|"definitelyUnsent"|"outcomeUnknown"="definitelyUnsent";
    try{if(this.allows(proof))outcome=this.options.onWire(proof,body);}catch{outcome="outcomeUnknown";}finally{this.active=null;}
    return JSON.stringify({outcome});
  }
  allows(proof:CombatProof){if(!this.active||this.active.claimed||JSON.stringify(proof)!==JSON.stringify(this.active.proof)||!this.fresh()||!this.sent||!sameIdentity(proof.identity,this.sent.identity)||proof.modelRevision!==this.sent.modelRevision||proof.map!==this.sent.map)return false;
    if(proof.skillId!==null){const matches=this.raw!.map((value,index)=>({value:value as Record<string,unknown>,id:object(value)&&Object.hasOwn(value,"id")?value.id:index})).filter(r=>r.id===proof.skillId);const spells=this.raw!.filter(r=>object(r)&&r.spell===proof.spell);if(matches.length!==1||spells.length!==1||matches[0].value.spell!==proof.spell||matches[0].value.hotkey!==proof.slot)return false;}
    if(proof.command.type==="magic"&&(proof.command.objectId!==proof.identity.playerObjectId||proof.command.spell!==proof.spell))return false;
    if(proof.targetId&& !this.sent.actors.some(a=>a.objectId===String(proof.targetId)))return false;return true;
  }
  claim(proof:CombatProof,body:string){if(!this.allows(proof)||this.active?.body!==body)return false;this.active!.claimed=true;return true;}
  withdraw(){const wasSent=Boolean(this.sent&&this.owns());if(this.sent&&this.owns()){try{this.options.runtime.withdrawMir2CombatInputSnapshot?.(JSON.stringify(this.sent.identity));}catch{/* remains locally withdrawn */}}this.sent=null;this.modelKey="";this.active=null;this.options.onReady(false);if(wasSent)this.options.onClear();}
  stop(){if(this.stopped)return;this.clearUiHeld();this.withdraw();this.stopped=true;if(this.owns()){try{this.options.runtime.clearMir2CombatInputIntentSink?.();}catch{/* revoked locally */}owners().delete(this.options.runtime);}}
}
