// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module sk_spike::dapp_key {
    use std::type_name;
    use sui::address;
    use std::ascii::String;

    /// DappKey — package-level authorization token for this DApp.
    ///
    /// SECURITY: `new()` is intentionally `public(package)`.
    /// Only code compiled into this package can construct a DappKey instance.
    /// All framework write functions (`set_record`, `set_field`,
    /// `take_record`, `create_user_storage`, …) require `_auth: DappKey`
    /// as proof that the call originated from inside this package — an
    /// external PTB cannot fabricate that proof.
    ///
    /// NEVER change `new()` to `public`, and never accept a DappKey
    /// value as a parameter from an external caller.  Either mistake removes
    /// every package-level access guard, allowing any PTB to write arbitrary
    /// user data or register UserStorages without going through the DApp's
    /// own entry functions.

    public struct DappKey has copy, drop {}

    /// Constructs an authorization token. Callable only from within this package.
    /// Pass the result as `_auth` to any framework function that requires it.
    public(package) fun new(): DappKey {
        DappKey {}
    }

    public fun to_string(): String {
        type_name::with_defining_ids<DappKey>().into_string()
    }

    public fun package_id(): address {
        let package_id_str = type_name::with_defining_ids<DappKey>().address_string();
        address::from_ascii_bytes(package_id_str.as_bytes())
    }

    public fun eq<DappKey1: copy + drop, DappKey2: copy + drop>(_: &DappKey1, _: &DappKey2): bool {
        type_name::with_defining_ids<DappKey1>() == type_name::with_defining_ids<DappKey2>()
    }
}
