// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module sk_spike::deploy_hook {
    use dubhe::dapp_service::DappStorage;

    public(package) fun run(_dapp_storage: &mut DappStorage, _ctx: &mut TxContext) {
        // Settlement mode: USER_PAYS — users pay transaction fees at settlement time.
    // The framework admin sets the revenue share via set_dapp_revenue_share.
    // Initialise any DappStorage-level defaults here (e.g. resource starting values).
    }
}