/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const getMir2RendererBackend: () => [number, number];
export const setMir2WorldState: (a: number, b: number) => void;
export const setMir2EntityRenderState: (a: number, b: number) => void;
export const setMir2EntityRenderAtlas: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const setMir2MapRenderState: (a: number, b: number) => void;
export const setMir2MapRenderAtlas: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const bootMir2Runtime: () => void;
export const setMir2MapCameraOffset: (a: number, b: number) => void;
export const setMir2StatusSink: (a: any) => void;
export const clearMir2StatusSink: () => void;
export const wasm_bindgen__convert__closures_____invoke__h42bf88799d610114: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hedeb5dba1c5a2e05: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1156e0773f81c68b: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1156e0773f81c68b_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1156e0773f81c68b_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1156e0773f81c68b_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1156e0773f81c68b_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1156e0773f81c68b_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1156e0773f81c68b_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1156e0773f81c68b_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28bcdfc0300fcc20: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
