// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module mir2_mine::config {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::DappStorage;
    use dubhe::dapp_system;
    use mir2_mine::dapp_key;
    use mir2_mine::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"config";
    const OFFCHAIN: bool = false;

    public struct Config has copy, drop, store {
        map_id: u32,
        mine_set: u8,
        max_stones: u32,
        regen_secs: u32,
        hit_rate: u8,
        drop_rate: u8,
    }

    public fun new(map_id: u32, mine_set: u8, max_stones: u32, regen_secs: u32, hit_rate: u8, drop_rate: u8): Config {
        Config {
            map_id,
            mine_set,
            max_stones,
            regen_secs,
            hit_rate,
            drop_rate,
        }
    }

    public fun map_id(self: &Config): u32 {
        self.map_id
    }

    public fun mine_set(self: &Config): u8 {
        self.mine_set
    }

    public fun max_stones(self: &Config): u32 {
        self.max_stones
    }

    public fun regen_secs(self: &Config): u32 {
        self.regen_secs
    }

    public fun hit_rate(self: &Config): u8 {
        self.hit_rate
    }

    public fun drop_rate(self: &Config): u8 {
        self.drop_rate
    }

    public fun update_map_id(self: &mut Config, map_id: u32) {
        self.map_id = map_id
    }

    public fun update_mine_set(self: &mut Config, mine_set: u8) {
        self.mine_set = mine_set
    }

    public fun update_max_stones(self: &mut Config, max_stones: u32) {
        self.max_stones = max_stones
    }

    public fun update_regen_secs(self: &mut Config, regen_secs: u32) {
        self.regen_secs = regen_secs
    }

    public fun update_hit_rate(self: &mut Config, hit_rate: u8) {
        self.hit_rate = hit_rate
    }

    public fun update_drop_rate(self: &mut Config, drop_rate: u8) {
        self.drop_rate = drop_rate
    }

    public fun has(dapp_storage: &DappStorage, mine_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        dapp_system::has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has(dapp_storage: &DappStorage, mine_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        dapp_system::ensure_has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has_not(dapp_storage: &DappStorage, mine_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        dapp_system::ensure_has_not_global_record<DappKey>(dapp_storage, key_tuple)
    }
  

    public(package) fun delete(dapp_storage: &mut DappStorage, mine_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        dapp_system::delete_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, vector[b"map_id", b"mine_set", b"max_stones", b"regen_secs", b"hit_rate", b"drop_rate"]);
    }

    public fun get_map_id(dapp_storage: &DappStorage, mine_id: u64): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let map_id_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"map_id");
        let mut map_id_bcs = sui::bcs::new(map_id_raw);
        let map_id = sui::bcs::peel_u32(&mut map_id_bcs);
        map_id
    }

    public(package) fun set_map_id(dapp_storage: &mut DappStorage, mine_id: u64, map_id: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let value = to_bytes(&map_id);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"map_id", value);
    }

    public fun get_mine_set(dapp_storage: &DappStorage, mine_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let mine_set_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"mine_set");
        let mut mine_set_bcs = sui::bcs::new(mine_set_raw);
        let mine_set = sui::bcs::peel_u8(&mut mine_set_bcs);
        mine_set
    }

    public(package) fun set_mine_set(dapp_storage: &mut DappStorage, mine_id: u64, mine_set: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let value = to_bytes(&mine_set);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"mine_set", value);
    }

    public fun get_max_stones(dapp_storage: &DappStorage, mine_id: u64): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let max_stones_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"max_stones");
        let mut max_stones_bcs = sui::bcs::new(max_stones_raw);
        let max_stones = sui::bcs::peel_u32(&mut max_stones_bcs);
        max_stones
    }

    public(package) fun set_max_stones(dapp_storage: &mut DappStorage, mine_id: u64, max_stones: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let value = to_bytes(&max_stones);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"max_stones", value);
    }

    public fun get_regen_secs(dapp_storage: &DappStorage, mine_id: u64): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let regen_secs_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"regen_secs");
        let mut regen_secs_bcs = sui::bcs::new(regen_secs_raw);
        let regen_secs = sui::bcs::peel_u32(&mut regen_secs_bcs);
        regen_secs
    }

    public(package) fun set_regen_secs(dapp_storage: &mut DappStorage, mine_id: u64, regen_secs: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let value = to_bytes(&regen_secs);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"regen_secs", value);
    }

    public fun get_hit_rate(dapp_storage: &DappStorage, mine_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let hit_rate_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"hit_rate");
        let mut hit_rate_bcs = sui::bcs::new(hit_rate_raw);
        let hit_rate = sui::bcs::peel_u8(&mut hit_rate_bcs);
        hit_rate
    }

    public(package) fun set_hit_rate(dapp_storage: &mut DappStorage, mine_id: u64, hit_rate: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let value = to_bytes(&hit_rate);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"hit_rate", value);
    }

    public fun get_drop_rate(dapp_storage: &DappStorage, mine_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let drop_rate_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"drop_rate");
        let mut drop_rate_bcs = sui::bcs::new(drop_rate_raw);
        let drop_rate = sui::bcs::peel_u8(&mut drop_rate_bcs);
        drop_rate
    }

    public(package) fun set_drop_rate(dapp_storage: &mut DappStorage, mine_id: u64, drop_rate: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let value = to_bytes(&drop_rate);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"drop_rate", value);
    }

    public fun get(dapp_storage: &DappStorage, mine_id: u64): (u32, u8, u32, u32, u8, u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let map_id_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"map_id");
        let mut map_id_bcs = sui::bcs::new(map_id_raw);
        let map_id = sui::bcs::peel_u32(&mut map_id_bcs);
        let mine_set_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"mine_set");
        let mut mine_set_bcs = sui::bcs::new(mine_set_raw);
        let mine_set = sui::bcs::peel_u8(&mut mine_set_bcs);
        let max_stones_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"max_stones");
        let mut max_stones_bcs = sui::bcs::new(max_stones_raw);
        let max_stones = sui::bcs::peel_u32(&mut max_stones_bcs);
        let regen_secs_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"regen_secs");
        let mut regen_secs_bcs = sui::bcs::new(regen_secs_raw);
        let regen_secs = sui::bcs::peel_u32(&mut regen_secs_bcs);
        let hit_rate_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"hit_rate");
        let mut hit_rate_bcs = sui::bcs::new(hit_rate_raw);
        let hit_rate = sui::bcs::peel_u8(&mut hit_rate_bcs);
        let drop_rate_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"drop_rate");
        let mut drop_rate_bcs = sui::bcs::new(drop_rate_raw);
        let drop_rate = sui::bcs::peel_u8(&mut drop_rate_bcs);
        (map_id, mine_set, max_stones, regen_secs, hit_rate, drop_rate)
    }

    public(package) fun set(dapp_storage: &mut DappStorage, mine_id: u64, map_id: u32, mine_set: u8, max_stones: u32, regen_secs: u32, hit_rate: u8, drop_rate: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let field_names = vector[b"map_id", b"mine_set", b"max_stones", b"regen_secs", b"hit_rate", b"drop_rate"];
        let value_tuple = encode(map_id, mine_set, max_stones, regen_secs, hit_rate, drop_rate);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun get_struct(dapp_storage: &DappStorage, mine_id: u64): Config {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let map_id_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"map_id");
        let mut map_id_bcs = sui::bcs::new(map_id_raw);
        let map_id = sui::bcs::peel_u32(&mut map_id_bcs);
        let mine_set_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"mine_set");
        let mut mine_set_bcs = sui::bcs::new(mine_set_raw);
        let mine_set = sui::bcs::peel_u8(&mut mine_set_bcs);
        let max_stones_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"max_stones");
        let mut max_stones_bcs = sui::bcs::new(max_stones_raw);
        let max_stones = sui::bcs::peel_u32(&mut max_stones_bcs);
        let regen_secs_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"regen_secs");
        let mut regen_secs_bcs = sui::bcs::new(regen_secs_raw);
        let regen_secs = sui::bcs::peel_u32(&mut regen_secs_bcs);
        let hit_rate_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"hit_rate");
        let mut hit_rate_bcs = sui::bcs::new(hit_rate_raw);
        let hit_rate = sui::bcs::peel_u8(&mut hit_rate_bcs);
        let drop_rate_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"drop_rate");
        let mut drop_rate_bcs = sui::bcs::new(drop_rate_raw);
        let drop_rate = sui::bcs::peel_u8(&mut drop_rate_bcs);
        Config { map_id, mine_set, max_stones, regen_secs, hit_rate, drop_rate }
    }

    public(package) fun set_struct(dapp_storage: &mut DappStorage, mine_id: u64, config: Config) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&mine_id));
        let field_names = vector[b"map_id", b"mine_set", b"max_stones", b"regen_secs", b"hit_rate", b"drop_rate"];
        let value_tuple = encode_struct(config);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun encode(map_id: u32, mine_set: u8, max_stones: u32, regen_secs: u32, hit_rate: u8, drop_rate: u8): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&map_id));
        value_tuple.push_back(to_bytes(&mine_set));
        value_tuple.push_back(to_bytes(&max_stones));
        value_tuple.push_back(to_bytes(&regen_secs));
        value_tuple.push_back(to_bytes(&hit_rate));
        value_tuple.push_back(to_bytes(&drop_rate));
        value_tuple
    }

    public fun encode_struct(config: Config): vector<vector<u8>> {
        encode(config.map_id, config.mine_set, config.max_stones, config.regen_secs, config.hit_rate, config.drop_rate)
    }

    public fun decode(data: vector<u8>): Config {
        let mut bcs_type = sui::bcs::new(data);
        let map_id = sui::bcs::peel_u32(&mut bcs_type);
        let mine_set = sui::bcs::peel_u8(&mut bcs_type);
        let max_stones = sui::bcs::peel_u32(&mut bcs_type);
        let regen_secs = sui::bcs::peel_u32(&mut bcs_type);
        let hit_rate = sui::bcs::peel_u8(&mut bcs_type);
        let drop_rate = sui::bcs::peel_u8(&mut bcs_type);
        Config {
            map_id,
            mine_set,
            max_stones,
            regen_secs,
            hit_rate,
            drop_rate,
        }
    }
}