// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module mir2_mine::ore_balance {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use mir2_mine::dapp_key;
    use mir2_mine::dapp_key::DappKey;
    use mir2_mine::ore_kind::{OreKind};

    const TABLE_NAME: vector<u8> = b"ore_balance";
    const OFFCHAIN: bool = false;

    public fun has(user_storage: &UserStorage, ore_kind: OreKind): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&ore_kind));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, ore_kind: OreKind) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&ore_kind));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, ore_kind: OreKind) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&ore_kind));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ore_kind: OreKind, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&ore_kind));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"amount"], ctx);
    }

    public fun get(user_storage: &UserStorage, ore_kind: OreKind): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&ore_kind));
        let amount_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"amount");
        let mut amount_bcs = sui::bcs::new(amount_raw);
        let value = sui::bcs::peel_u64(&mut amount_bcs);
        value
    }

    public(package) fun set(user_storage: &mut UserStorage, ore_kind: OreKind, value: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&ore_kind));
        let field_names = vector[b"amount"];
        let value_tuple = encode(value);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(value: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&value));
        value_tuple
    }


    // ─── keys: mint (developer provides keys; framework ensures no duplicate) ─
    // Choosing the ID strategy (fresh address, counter, coordinate pack, etc.)
    // is intentionally left to the caller.
    public(package) fun mint(
        user_storage: &mut UserStorage,
        ore_kind: OreKind, amount: u64,
        ctx: &mut TxContext,
    ) {
        ensure_has_not(user_storage, ore_kind);
        set(user_storage, ore_kind, amount, ctx);
    }
}