import test from 'node:test';
import assert from 'node:assert/strict';
import { gzipSync } from 'node:zlib';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { decodeCatalogBatch, decodePlaytestFrame, CATALOG_GZIP_CAPABILITY,
  MAX_CATALOG_DECODED_BYTES, MAX_CATALOG_ENVELOPES, MAX_CATALOG_WIRE_BYTES } from './playtest-catalog-transport.mjs';
import { NativeResumeClient, validateResumeControl } from './playtest-native-resume-smoke.mjs';
import { CapacityClient } from './playtest-capacity-soak.mjs';
const { Server: WebSocketServer } = createRequire(import.meta.url)('next/dist/compiled/ws');

const envelope = (packet = 'NewItemInfo', index = 1) => ({ type: 'packet', packet, payload: { index, name: '药品 Potion' } });
function rawBatch(body, count = 1, length = body.length) {
  const header = Buffer.alloc(16); header.write('M2CATGZ1'); header.writeUInt32LE(length, 8); header.writeUInt32LE(count, 12);
  return Buffer.concat([header, gzipSync(body)]);
}
function batch(texts) {
  return rawBatch(Buffer.concat(texts.map(text => {
    const bytes = Buffer.from(text), prefix = Buffer.alloc(4); prefix.writeUInt32LE(bytes.length);
    return Buffer.concat([prefix, bytes]);
  })), texts.length);
}
const encoded = messages => batch(messages.map(message => JSON.stringify(message)));

test('catalog framing preserves Unicode, fields and original envelope order', () => {
  const messages = ['NewItemInfo', 'NewRecipeInfo', 'GameShopInfo', 'NewQuestInfo'].map(envelope);
  assert.deepEqual(decodeCatalogBatch(encoded(messages)), messages);
  assert.deepEqual(decodeCatalogBatch(new Uint8Array(encoded(messages))), messages);
  assert.deepEqual(decodePlaytestFrame(encoded(messages), true), messages);
});

test('Rust flate2 reference fixture decodes with the identical Unicode and order in Node', () => {
  // This fixture is generated by the shared Rust codec, not a second JS gzip.
  const full = Buffer.from('4d32434154475a319c000000020000001f8b08000000000004ff858c410a40401846e728fad676166a36d63662e10013bf1266945f48b370002b07712ae518a22c65f77af55e2a8498c1534b9068555611c37d4122a221646a425d98474fb55139e48c52e73442fa2eb46aeef65cf7635b9cd8706934ac0d7ec7494f1d7f9e3d6b2f7d6d409c9c000000', 'hex');
  assert.deepEqual(decodeCatalogBatch(full), [
    { type: 'packet', packet: 'NewItemInfo', payload: { index: 7, name: '药品 Potion' } },
    { type: 'packet', packet: 'NewQuestInfo', payload: { index: 3 } },
  ]);
});

test('legacy text stays text and binary requires explicit transport capability', () => {
  const text = JSON.stringify({ type: 'worldSnapshot', payload: { mapFileName: '0' } });
  assert.deepEqual(decodePlaytestFrame(text), [JSON.parse(text)]);
  assert.deepEqual(decodePlaytestFrame(text, true), [JSON.parse(text)]);
  assert.throws(() => decodePlaytestFrame(encoded([envelope()])), /Unnegotiated/);
  assert.doesNotThrow(() => validateResumeControl({ type: 'clientCapabilities', capabilities: ['nativeResumeV1', CATALOG_GZIP_CAPABILITY] }));
  for (const capabilities of [[CATALOG_GZIP_CAPABILITY], ['nativeResumeV1', 'unknown'],
    ['nativeResumeV1', CATALOG_GZIP_CAPABILITY, CATALOG_GZIP_CAPABILITY]]) {
    assert.throws(() => validateResumeControl({ type: 'clientCapabilities', capabilities }));
  }
});

test('entire batch must be catalog envelopes before any entry can be applied', () => {
  for (const message of [{ type: 'identitySession', token: 'private-must-not-leak' },
    { type: 'packet', packet: 'UserInformation', payload: {} },
    { type: 'packet', packet: 'NewItemInfo', payload: null },
    { type: 'packet', packet: 'NewQuestInfo', payload: [] },
    { type: 'resumeCredential', credential: 'private-must-not-leak' }]) {
    let applied = 0;
    assert.throws(() => { for (const item of decodeCatalogBatch(encoded([envelope(), message]))) applied++; },
      error => error.message === 'Invalid bounded gateway catalog batch');
    assert.equal(applied, 0);
  }
  assert.throws(() => decodeCatalogBatch(batch(['private-must-not-leak'])),
    error => error.message === 'Invalid bounded gateway catalog batch');
});

test('gzip CRC, length, truncation, appended bytes and additional members fail closed', () => {
  const valid = encoded([envelope()]);
  const crcBad = Buffer.from(valid); crcBad[crcBad.length - 8] ^= 1;
  const sizeBad = Buffer.from(valid); sizeBad[sizeBad.length - 4] ^= 1;
  const decodedBad = Buffer.from(valid); decodedBad.writeUInt32LE(valid.readUInt32LE(8) - 1, 8);
  const countBad = Buffer.from(valid); countBad.writeUInt32LE(2, 12);
  const magicBad = Buffer.from(valid); magicBad[0] ^= 1;
  for (const bad of [crcBad, sizeBad, decodedBad, countBad, magicBad, valid.subarray(0, valid.length - 1),
    Buffer.concat([valid, Buffer.from([0])]), Buffer.concat([valid, gzipSync('second-member')])]) {
    assert.throws(() => decodeCatalogBatch(bad), /Invalid bounded/);
  }
});

test('decoded, wire and count limits prevent oversized or explosive allocation', () => {
  const oversized = rawBatch(Buffer.alloc(MAX_CATALOG_DECODED_BYTES + 1, 65), 1, MAX_CATALOG_DECODED_BYTES);
  const badClaim = rawBatch(Buffer.from('abcdef'), 1, MAX_CATALOG_DECODED_BYTES + 1);
  for (const bad of [oversized, badClaim, rawBatch(Buffer.from('abcdef'), 0),
    rawBatch(Buffer.from('abcdef'), MAX_CATALOG_ENVELOPES + 1), Buffer.alloc(MAX_CATALOG_WIRE_BYTES + 1)]) {
    assert.throws(() => decodeCatalogBatch(bad), /Invalid bounded/);
  }
  const maximumCount = Array.from({ length: MAX_CATALOG_ENVELOPES }, (_, index) => envelope('NewItemInfo', index));
  assert.equal(decodeCatalogBatch(encoded(maximumCount)).length, MAX_CATALOG_ENVELOPES);
});

test('text length, UTF8, empty entries and unused decoded bytes are rejected', () => {
  const invalidUtf8 = Buffer.from([2, 0, 0, 0, 0xc0, 0xaf]);
  for (const body of [invalidUtf8, Buffer.from([0, 0, 0, 0, 0]), Buffer.from([6, 0, 0, 0, 1]),
    Buffer.from([1, 0, 0, 0, 49, 0])]) assert.throws(() => decodeCatalogBatch(rawBatch(body)), /Invalid bounded/);
});

test('a high-bit gzip flag cannot bypass header validation', () => {
  const bad = encoded([envelope()]); bad[19] |= 32;
  assert.throws(() => decodeCatalogBatch(bad), /Invalid bounded/);
});

async function socketFixture(run, batchMessages, Client = NativeResumeClient) {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'mir2-catalog-'));
  const server = new WebSocketServer({ host: '127.0.0.1', port: 0 });
  await new Promise(resolve => server.once('listening', resolve));
  server.on('connection', socket => socket.on('message', raw => {
    const command = JSON.parse(raw);
    if (command.type === 'clientVersion') {
      socket.send(JSON.stringify({ type: 'packet', packet: 'Connected', payload: {} }));
      socket.send(JSON.stringify({ type: 'packet', packet: 'ClientVersion', payload: { result: 1 } }));
    } else if (command.type === 'clientCapabilities') {
      socket.send(encoded(batchMessages));
      socket.send(JSON.stringify({ type: 'packet', packet: 'TimeOfDay', payload: { lights: 'Day' } }));
    }
  }));
  const endpoint = `ws://127.0.0.1:${server.address().port}/ws`;
  const client = Client === CapacityClient ? new CapacityClient(endpoint, { name: 'CatalogActor', accountId: 'catalog-actor', password: 'private-fixture' },
    { guard: { assert() {} }, writer: { add() {} }, add() {} }) : new NativeResumeClient(endpoint, 'catalog', path.join(directory, 'trace.jsonl'));
  try { await client.connect(); await run(client); }
  finally {
    await client.close();
    for (const socket of server.clients) socket.terminate();
    await new Promise(resolve => server.close(resolve));
    await fs.unlink(path.join(directory, 'trace.jsonl')).catch(error => { if (error.code !== 'ENOENT') throw error; });
    await fs.rmdir(directory);
  }
}

test('real WebSocket applies negotiated catalog batch in order between legacy Text messages', async () => {
  const messages = [envelope('NewItemInfo'), envelope('NewQuestInfo')];
  await socketFixture(async client => {
    client.control({ type: 'clientCapabilities', capabilities: ['nativeResumeV1', CATALOG_GZIP_CAPABILITY] });
    await client.wait(() => client.events.some(event => event.packet === 'TimeOfDay'), 'catalog and following text', 2000);
    assert.equal(client.failure, undefined);
    assert.deepEqual(client.events.filter(event => event.direction === 'received').map(event => event.packet),
      ['Connected', 'ClientVersion', 'NewItemInfo', 'NewQuestInfo', 'TimeOfDay']);
  }, messages);
});

test('real WebSocket rejects an unnegotiated batch without observing any catalog entry', async () => {
  await socketFixture(async client => {
    client.control({ type: 'clientCapabilities', capabilities: ['nativeResumeV1'] });
    await assert.rejects(client.wait(() => false, 'unnegotiated batch', 2000), /Unnegotiated/);
    assert.equal(client.events.filter(event => event.packet === 'NewItemInfo').length, 0);
  }, [envelope()]);
});

test('real WebSocket rejects a malformed second envelope without partially applying the first', async () => {
  await socketFixture(async client => {
    client.control({ type: 'clientCapabilities', capabilities: ['nativeResumeV1', CATALOG_GZIP_CAPABILITY] });
    await assert.rejects(client.wait(() => false, 'invalid batch', 2000), /Invalid bounded/);
    assert.equal(client.events.filter(event => event.packet === 'NewItemInfo').length, 0);
    assert.equal(client.events.filter(event => event.type === 'identitySession').length, 0);
    assert.equal(client.events.filter(event => event.packet === 'TimeOfDay').length, 0);
  }, [envelope(), { type: 'identitySession', token: 'private-must-not-leak' }]);
});

test('actual CapacityClient negotiation permits compressed catalogs and counts physical wire bytes once', async () => {
  const messages = [envelope('NewItemInfo'), envelope('NewQuestInfo')];
  await socketFixture(async client => {
    await client.wait(() => client.events.some(event => event.packet === 'TimeOfDay'), 'capacity catalog receipt', 2000);
    assert.equal(client.catalogGzipOptedIn, true);
    assert.equal(client.failure, undefined);
    assert.deepEqual(client.events.filter(event => event.direction === 'received').map(event => event.packet),
      ['Connected', 'ClientVersion', 'NewItemInfo', 'NewQuestInfo', 'TimeOfDay']);
    const text = [{ type: 'packet', packet: 'Connected', payload: {} },
      { type: 'packet', packet: 'ClientVersion', payload: { result: 1 } },
      { type: 'packet', packet: 'TimeOfDay', payload: { lights: 'Day' } }];
    assert.equal(client.bytes.received, text.reduce((sum, item) => sum + Buffer.byteLength(JSON.stringify(item)), encoded(messages).length));
  }, messages, CapacityClient);
});

test('malformed Text errors never quote remote payload into operator reports', () => {
  assert.throws(() => decodePlaytestFrame('{"token":"private-must-not-leak"} trailing'),
    error => error.message === 'Invalid gateway text frame');
});
