// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module mir2_mine::error {
    #[error]
    const EMineNotFound: vector<u8> = b"Mine not found";
    public fun MineNotFound(condition: bool) { assert!(condition, EMineNotFound) }

    #[error]
    const EMineExhausted: vector<u8> = b"Mine has no stones left";
    public fun MineExhausted(condition: bool) { assert!(condition, EMineExhausted) }

    #[error]
    const EBadNonce: vector<u8> = b"Replay or out-of-order nonce";
    public fun BadNonce(condition: bool) { assert!(condition, EBadNonce) }

    #[error]
    const EInsufficientFee: vector<u8> = b"Attached SUI is less than the required fee";
    public fun InsufficientFee(condition: bool) { assert!(condition, EInsufficientFee) }

    #[error]
    const EEmissionCapReached: vector<u8> = b"Epoch emission cap reached";
    public fun EmissionCapReached(condition: bool) { assert!(condition, EEmissionCapReached) }

    #[error]
    const ENotAdmin: vector<u8> = b"Caller does not hold the admin capability";
    public fun NotAdmin(condition: bool) { assert!(condition, ENotAdmin) }

    #[error]
    const EBadSwings: vector<u8> = b"Swings must be greater than zero";
    public fun BadSwings(condition: bool) { assert!(condition, EBadSwings) }

    #[error]
    const EInsufficientOre: vector<u8> = b"Insufficient ore balance to redeem";
    public fun InsufficientOre(condition: bool) { assert!(condition, EInsufficientOre) }

    #[error]
    const EBadAmount: vector<u8> = b"Amount must be greater than zero";
    public fun BadAmount(condition: bool) { assert!(condition, EBadAmount) }
}
